In [134]:
import pandas as pd
import numpy as np

In [135]:
pd.set_option('display.max_rows',None)
pd.set_option("display.max_columns",None)

In [136]:
houses = pd.read_csv('houses.csv')

In [137]:
df = houses.copy()

In [138]:
df

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272
5,20 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/20-bhk-bedroom-indepen...,NaN,4.5 Crore,"₹ 39,062/sq.ft.",(107 sq.m.) Plot Area,Plot area 128(107.02 sq.m.),20 Bedrooms,20 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",Best for investment purpose. 3l rupees monthly...,"['1 Water Purifier', '1 Fridge', '20 Fan', '1 ...","['Water Storage', 'Park', 'Visitor Parking', '...","['Environment5 out of 5', 'Lifestyle5 out of 5...",V69218808
6,5 Bedroom House for sale in Sector 66 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,12 Crore,"₹ 37,037/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,"Servant Room,Pooja Room,Store Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,East,0 to 1 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Available for sale 5bhk independent house in e...,"['4 Wardrobe', '1 Water Purifier', '6 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5...",G55931988
7,16 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/16-bhk-bedroom-indepen...,Luxury DLF City Floors,20 Crore,"₹ 48,889/sq.ft.",(418 sq.m.) Plot Area,Plot area 500(418.06 sq.m.),16 Bedrooms,16 Bathrooms,3+ Balconies,Servant Room,"DLF Phase 1, Gurgaon, Haryana",4 Floors,NaN,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",Prime location on dlf phase - 1 builder floor ...,"['16 Wardrobe', '26 Fan', '1 Exhaust Fan', '16...","['High Ceiling Height', 'Park', 'Visitor Parki...","['Environment5 out of 5', 'Lifestyle5 out of 5...",E67952012
8,6 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,10.85 Crore,"₹ 38,150/sq.ft.",(264 sq.m.) Plot Area,Plot area 316(264.22 sq.m.),6 Bedrooms,6 Bathrooms,1 Balcony,Store Room,"DLF Phase 2, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...","6 bhk kothi in dlf phase 2, gurgaon available ...","['4 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",U69218678
9,3 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/3-bhk-bedroom-independ...,Sushant Lok 1 Builder Floors,1.95 Crore,"₹ 10,077/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"C Block Small Nos, Sushant Lok Phase 1, Gurgao...",4 Floors,West,0 to 1 Year Old,"['Huda city centre metro station', 'Sector 42-...",Brand new builder floor at very reasonable pri...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Lifestyle5 out of 5...",L69688060
10,4 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,4.45 Crore,"₹ 32,963/sq.ft.",(125 sq.m.) Plot Area,Plot area 150(125.42 sq.m.),4 Bedrooms,3 Bathrooms,3+ Balconies,Store Room,"001, DLF Phase 2, Gurgaon, Haryana",2 Floors,West,5 to 10 Year Old,"['Vodafone belvedere towers metro station', 'D...",Available 4bhk 150sq.Yd very well maintained v...,"['3 Wardrobe', '3 Fan', '3 Geyser', '3 Light',...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S69606324
11,6 Bedroom House for sale in DLF Phase 4,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,9 Crore,"₹ 27,778/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),6 Bedrooms,7 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Near Galleria, DLF Phase 4, Gurgaon, Haryana",3 Floors,North,5 to 10 Year Old,"['Dlf phase 1 metro station', 'Huda city centr...",This is a old builtup property can be livable ...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",E69552472
12,13 Bedroom House for sale in DLF Phase 3,https://www.99acres.com/13-bhk-bedroom-indepen...,DLF City Plots Phase 3,5 Crore,"₹ 34,083/sq.ft.",(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),13 Bedrooms,13 Bathrooms,3+ Balconies,Pooja Room,"Dlf Phase 3, DLF Phase 3, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Dlf phase 3 metro station', 'Micromax moulsa...",This is located in dlf phase 3 and very near f...,"['1 Water Purifier', '1 Fridge', '21 Fan', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle5 out of 5...",T69505836
13,5 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,15 Crore,"₹ 33,200/sq.ft.",(420 sq.m.) Plot Area,Plot area 502(419.74 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","A Block, DLF Phase 1, Gurgaon, Haryana",3 Floors,North,5 to 10 Year Old,"['Guru dronacharya metro station', 'Dlf phase ...",Genuine livable kothi at the rate of plot only...,"['5 Wardrobe', '9 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",Z69504416
14,5 Bedroom House for sale in B Block Sushant Lo...,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,8.25 Crore,"₹ 30,556/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,"Study Room,Servant Room,Store Room,Pooja Room","Sushant Lok, B Block Sushant Lok Phase 1, Gurg...",3 Floors,West,5 to 10 Year Old,"['Iffco chowk metro station', 'Huda city centr...",Well maintained kothi very well lacated gated ...,"['5 Wardrobe', '10 Fan', '1 Exhaust Fan', '5 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4.5 out of...",F69489716
15,6 Bedroom House for sale in New Palam Vihar Ph...,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,2 Crore,"₹ 14,914/sq.ft.",(125 sq.m.) Plot Area,Plot area 1341(124.58 sq.m.),6 Bedrooms,4 Bathrooms,3 Balconies,"Pooja Room,Study Room","New Palam Vihar Phase 1, Gurgaon, Haryana",3 Floors,East,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",East facing 2 fully made floor plus terrace. P...,"['6 Wardrobe', '9 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN,S69432458
16,9 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/9-bhk-bedroom-independ...,DLF City Plots Phase 2,10.75 Crore,"₹ 29,861/sq.ft.",(334 sq.m.) Plot Area,Plot area 400(334.45 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,"Servant Room,Pooja Room,Store Room","DLF Phase 2, Gurgaon, Haryana",3 Floors,South-West,10+ Year Old,"['Vodafone belvedere towers metro station', 'D...",This is located in dlf phase 2 very near from ...,"['5 Fan', '1 Exhaust Fan', '3 Light', 'No AC',...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment5 out of 5', 'Lifestyle5 out of 5...",U69430128
17,7 Bedroom House for sale in Sector 38 Gurgaon,https://www.99acres.com/7-bhk-bedroom-independ...,NaN,2.1 Crore,"₹ 23,333/sq.ft.",(84 sq.m.) Plot Area,Plot area 100(83.61 sq.m.),7 Bedrooms,7 Bathrooms,3+ Balconies,"Store Room,Pooja Room,Study Room","Sector 38 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Rajiv Chowk Mosque', 'Icici bank ATM', 'Stat...",Stilt plus 3 floors. 4 year old construction. ...,NaN,"['High Ceiling Height', 'Maintenance Staff', '...","['Environment4 out of 5', 'Lifestyle4 out of 5...",A68711470
18,4 Bedroom House for sale in Nirvana Country,https://www.99acres.com/4-bhk-bedroom-independ...,Unitech Espace,7.35 Crore,"₹ 41,762/sq.ft.",(201 sq.m.) Plot Area,Plot area 240(200.67 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Servant Room","Nirvana Country, Gurgaon, Haryana",3 Floors,South,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Sri Radhe Krish...",This is property is next to park and sunfacing.,"['5 Wardrobe', '1 Exhaust Fan', '4 Geyser', '9...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle5 out of 5...",G68255006
19,6 Bedroom House for sale in Uppals Southend,https://www.99acres.com/6-bhk-bedroom-independ...,NaN,4.45 Crore,"₹ 15,451/sq.ft.",(268 sq.m.) Plot Area,Plot area 320(267.56 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Uppals Southend, Gurgaon, Haryana",3 Floors,North,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Uppals southend, gurgaon, haryana for sale kot...","['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5...",X68250584
20,9 Bedroom House for sale in Sector 9 Gurgaon,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,3.4 Crore,"₹ 12,938/sq.ft.",(244 sq.m.) Plot Area,Plot area 292(244.15 sq.m.),9 Bedrooms,9 Bathrooms,3 Balconies,NaN,"Sector 9 Gurgaon, Gurgaon, Haryana",3 Floors,West,5 to 10 Year Old,"['State bank ATM', 'Esic Hospital Gurugram', '...",292 square yards triple story made 9 bhk house...,"['9 Wardrobe', '12 Fan', '1 Exhaust Fan', '50 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",O69749646
21,5 Bedroom House for sale in Sector 66 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Emaar MGF Marbella,12 Crore,"₹ 38,095/sq.ft.",(293 sq.m.) Plot Area,Plot area 350(292.64 sq.m.),5 Bedrooms,6 Bathrooms,3+ Balconies,"Store Room,Servant Room","Sector 66 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...",Looking to buy an independent house in gurgaon...,"['1 Exhaust Fan', '8 AC', '1 Modular Kitchen',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment3 out of 5', 'Lifestyle4 out of 5...",R69735166
22,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,8.4 Crore,"₹ 25,926/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,"Pooja Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",It's 4bhk villa in posh society known as tatva...,"['4 Wardrobe', '8 Fan', '1 Exhaust Fan', '5 Ge...","['Water Storage', 'Park', 'Piped-gas']","['Environment4 out of 5', 'Lifestyle4 out of 5...",F69407586
23,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Vipul Tatvam Villa,8.5 Crore,"₹ 26,235/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Pooja Room,Servant Room,Store Room","Sector 48 Gurgaon, Gurgaon, Haryana",NaN,East,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Three side open villa in tatvam villa sector-4...,"['1 Chimney', '1 Modular Kitchen', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",Q69361158
24,9 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,7.6 Crore,"₹ 38,760/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),9 Bedrooms,9 Bathrooms,3 Balconies,"Study Room,Pooja Room,Store Room","2/22, DLF Phase 2, Gurgaon, Haryana",4 Floors,East,1 to 5 Year Old,"['Vodafone belvedere towers metro station', 'D...",Sale - Kothi in gurgaon\n# dlf phase -2 ()\n# ...,"['1 Water Purifier', '9 Fan', '1 Exhaust Fan',...","['Security / Fire Alarm', 'Water purifier', 'H...","['Environment5 out of 5', 'Lifestyle5 out of 5...",I67974640
25,5 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/5-bhk-bedroom-independ...,Ansal Sushant Lok Plots4.1 ★,7 Crore,"₹ 25,926/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),5 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","C Block, Sushant Lok Phase 1, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...",This kothi is excellent location near by metro...,"['20 Wardrobe', '11 Fan', '1 Exhaust Fan', '7 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",P69749546
26,5 Bedroom House for sale in Sector 4 Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Grover Homes Sec 4,4.75 Crore,"₹ 9,374/sq.ft.",(471 sq.m.) Plot Area,Plot area 563(470.74 sq.m.),5 Bedrooms,5 Bathrooms,1 Balcony,"Pooja Room,Study Room,Servant Room","Sector 4 Gurgaon, Gurgaon, Haryana",1 Floors,South-East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",This property is old connection as a plot rate...,"['16 Wardrobe', '9 Fan', '1 Exhaust Fan', '4 G...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",S69710120
27,9 Bedroom House for sale in Sector 9 Gurgaon,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,3.5 Crore,"₹ 13,410/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,Study Room,"122001, Sector 9 Gurgaon, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['State bank ATM', 'Esic Hospital Gurugram', '...",House\nNew listing\nAbout property\nAddress: S...,"['3 Wardrobe', '1 Modular Kitchen', 'No AC', '...","['Feng Shui / Vaastu Compliant', 'Recently Ren...","['Environment4 out of 5', 'Lifestyle4 out of 5...",W66824186
28,9 Bedroom House for sale in Sector 40 Gurgaon,https://www.99acres.com/9-bhk-bedroom-independ...,NaN,5 Crore,"₹ 21,124/sq.ft.",(220 sq.m.) Plot Area,Plot area 263(219.9 sq.m.),9 Bedrooms,9 Bathrooms,3+ Balconies,"Servant Room,Store Room","7777, Sector 40 Gurgaon, Gurgaon, Haryana",3 Floors,North-West,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...",Its wonderfully made 3bhk on each floor with b...,"['10 Wardrobe', '21 Fan', '1 Exhaust Fan', '9 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",C69535484
29,5 Bedroom House for sale in Nirvana Country,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,10.56 Crore,"₹ 32,593/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),5 Bedrooms,5 Bathrooms,3 Balconies,Servant Room,"Nirvana Country, Gurgaon, Haryana",3 Floors,NaN,5 to 10 Year Old,"['Radhakrishna Shani Mandir', 'Standard charte...",Urgent for sale\nOn main wide road\nConfirm de...,NaN,"['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",J69645548
30,4 Bedroom House for sale in Sector 67 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Ansal API Esencia3.7 ★,5.46 Crore,"₹ 24,170/sq.ft.",(210 sq.m.) Plot Area,Plot area 251(209.87 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Store Room","C Block Ansal Esencia, Golf Course Ext Road, S...",2 Floors,East,1 to 5 Year Old,"['Proposed Metro corridor', 'N.H-8', 'Golf Cou...",Ansal esencia is a residential group housing p...,"['5 Wardrobe', '8 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4.5 out of...",J69714706
31,5 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,10 Crore,"₹ 37,037/sq.ft.",(251 sq.m.) Plot Area,Plot area 300(250.84 sq.m.),5 Bedrooms,6 Bathrooms,3 Balconies,"Store Room,Servant Room","N22, DLF Phase 2, Gurgaon, Haryana",3 Floors,North,10+ Year Old,"['Vodafone belvedere towers metro station', 'D...",A 5 bhk semi furnished independent kothi is av...,"['1 Water Purifier', '7 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",T70164790
32,10 Bedroom House for sale in DLF Phase 2,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,9 Crore,"₹ 28,490/sq.ft.",(293 sq.m.) Plot Area,Plot area 351(293.48 sq.m.),10 Bedrooms,10 Bathrooms,3 Balconies,Pooja Room,"M15, DLF Phase 2, Gurgaon, Haryana",3 Floors,East,10+ Year Old,"['Vodafone belvedere towers metro station', 'D...",A 5 bhk semi furnished independent house is av...,"['5 Wardrobe', '1 Water Purifier', '7 Fan', '1...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",A70164370
33,4 Bedroom House for sale in Hsiidc Plot Sector...,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,10 Crore,"₹ 122,222/sq.ft.",(84 sq.m.) Plot Area,Plot area 900(83.61 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Hsiidc Plot Sector 1 Imt Manesar, Gurgaon, Har...",1 Floors,North-East,undefined,NaN,Hsiidc plot for sae sec-1 imt manesar Plot siz...,NaN,"['Feng Shui / Vaastu Compliant', 'Piped-gas', ...",NaN,G68221332

In [139]:
df.shape

(1044, 21)

In [140]:
df.columns

Index(['property_name', 'link', 'society', 'price', 'rate', 'area',
       'areaWithType', 'bedRoom', 'bathroom', 'balcony', 'additionalRoom',
       'address', 'noOfFloor', 'facing', 'agePossession', 'nearbyLocations',
       'description', 'furnishDetails', 'features', 'rating', 'property_id'],
      dtype='object')

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [142]:
df.isnull().sum()

property_name        0
link                 0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
rating             137
property_id          8
dtype: int64

In [143]:
df.duplicated().sum()

np.int64(13)

In [144]:
df = df.drop_duplicates()

In [145]:
df['property_name'].value_counts()

property_name
4 Bedroom House for sale in Sector 109 Gurgaon                                           25
4 Bedroom House for sale in Sector 48 Gurgaon                                            20
5 Bedroom House for sale in Sector 109 Gurgaon                                           17
5 Bedroom House for sale in DLF Phase 2                                                  16
5 Bedroom House for sale in DLF Phase 1                                                  15
5 Bedroom House for sale in Sector 66 Gurgaon                                            14
4 Bedroom House for sale in Nirvana Country                                              13
4 Bedroom House for sale in Sector 66 Gurgaon                                            12
5 Bedroom House for sale in Nirvana Country                                              10
5 Bedroom House for sale in Sector 33 Gurgaon                                             9
4 Bedroom House for sale in DLF Phase 1                                                   9
4 Bedroom House for sale in Palam Vihar                                                   8
6 Bedroom House for sale in DLF Phase 1                                                   7
3 Bedroom House for sale in Nirvana Country                                               7
3 Bedroom House for sale in Sector 48 Gurgaon                                             7
9 Bedroom House for sale in DLF Phase 2                                                   7
4 Bedroom House for sale in Sector 70A Gurgaon                                            7
5 Bedroom House for sale in Laxman Vihar                                                  6
3 Bedroom House for sale in Laxman Vihar                                                  6
4 Bedroom House for sale in DLF Phase 3                                                   6
4 Bedroom House for sale in Sushant Lok Phase 3                                           6
3 Bedroom House for sale in Sector 109 Gurgaon                                            6
3 Bedroom House for sale in Rajendra Park                                                 6
4 Bedroom House for sale in Sector 82 Gurgaon                                             6
2 Bedroom House for sale in Laxman Vihar                                                  5
5 Bedroom House for sale in Sector 14 Gurgaon                                             5
4 Bedroom House for sale in DLF Phase 2                                                   5
5 Bedroom House for sale in Sector 48 Gurgaon                                             5
3 Bedroom House for sale in Sector 49 Gurgaon                                             5
3 Bedroom House for sale in Sector 4 Gurgaon                                              4
6 Bedroom House for sale in Uppals Southend                                               4
4 Bedroom House for sale in Sector 112 Gurgaon                                            4
4 Bedroom House for sale in Sector 26 Gurgaon                                             4
4 Bedroom House for sale in Sector 31 Gurgaon                                             4
3 Bedroom House for sale in Laxman Vihar Phase 2                                          4
3 Bedroom House for sale in Sector 14 Gurgaon                                             4
5 Bedroom House for sale in Sushant Lok Phase 1                                           4
2 Bedroom House for sale in Palam Vihar Extension                                         4
4 Bedroom House for sale in Sector 54 Gurgaon                                             4
6 Bedroom House for sale in DLF Phase 2                                                   4
16 Bedroom House for sale in DLF Phase 1                                                  4
6 Bedroom House for sale in Palam Vihar                                                   4
2 Bedroom House for sale in Laxman Vihar Phase 2                                          4
4 Bedroom House for sale in DLF Phase 4                                                   4
7 Bedroom House for sale in Sushant Lok Phase 1                                           3
7 Bedroom House for sale in Sector 109 Gurgaon                                            3
4 Bedroom House for sale in Sector 86 Gurgaon                                             3
8 Bedroom House for sale in Sector 46 Gurgaon                                             3
3 Bedroom House for sale in Sohna Road                                                    3
5 Bedroom House for sale in New Colony                                                    3
5 Bedroom House for sale in Uppals Southend                                               3
5 Bedroom House for sale in Sector 111 Gurgaon                                            3
3 Bedroom House for sale in Sector 73 Gurgaon                                             3
4 Bedroom House for sale in Sushant Lok Phase 1                                           3
12 Bedroom House for sale in DLF Phase 2                                                  3
12 Bedroom House for sale in DLF Phase 1                                                  3
3 Bedroom House for sale in Palam Vihar                                                   3
5 Bedroom House for sale in Sector 46 Gurgaon                                             3
4 Bedroom House for sale in Sector 46 Gurgaon                                             3
5 Bedroom House for sale in Sector 57 Gurgaon                                             3
4 Bedroom House for sale in Sector 92 Gurgaon                                             3
1 Bedroom House for sale in Sector 3A Gurgaon                                             3
3 Bedroom House for sale in Sector 70A Gurgaon                                            3
5 Bedroom House for sale in Mianwali Colony                                               3
8 Bedroom House for sale in DLF Phase 3                                                   3
4 Bedroom House for sale in Sector 17B Gurgaon                                            3
3 Bedroom House for sale in Ansal Plaza                                                   3
2 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 3
5 Bedroom House for sale in Sector 72 Gurgaon                                             3
5 Bedroom House for sale in Jyoti Park                                                    3
7 Bedroom House for sale in Sector 48 Gurgaon                                             3
3 Bedroom House for sale in Sector 38 Gurgaon                                             3
5 Bedroom House for sale in Sector 50 Gurgaon                                             3
3 Bedroom House for sale in Sushant Lok Phase 1                                           3
6 Bedroom House for sale in Sector 17 Gurgaon                                             3
10 Bedroom House for sale in Rajiv Nagar                                                  3
3 Bedroom House for sale in Sector 82 Gurgaon                                             3
1 Bedroom House for sale in Sector 39 Gurgaon                                             3
12 Bedroom House for sale in Uppals Southend                                              3
1 Bedroom House for sale in Sushant Lok Phase 1                                           3
3 Bedroom House for sale in Ashok Vihar                                                   3
4 Bedroom House for sale in Sector 103 Gurgaon                                            3
6 Bedroom House for sale in Sector 33 Gurgaon                                             3
6 Bedroom House for sale in Greenwood City                                                3
5 Bedroom House for sale in Palam Vihar                                                   3
6 Bedroom House for sale in Sushant Lok Phase 3                                           3
8 Bedroom House for sale in Palam Vihar                                                   2
12 Bedroom House for sale in Sector 56 Gurgaon                                            2
5 Bedroom House for sale in Greenwood City                                                2
4 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
10 Bedroom House for sale in South City 1                                                 2
3 Bedroom House for sale in Rosewood                                                      2
3 Bedroom House for sale in Sector 40 Gurgaon                                             2
4 Bedroom House for sale in Sector 55 Gurgaon                                             2
4 Bedroom House for sale in Sector 91 Gurgaon                                             2
5 Bedroom House for sale in Sector 56 Gurgaon                                             2
8 Bedroom House for sale in Sushant Lok Phase 1                                           2
9 Bedroom House for sale in South City 1                                                  2
3 Bedroom House for sale in Sector 7 Gurgaon                                              2
6 Bedroom House for sale in Sector 22 Gurgaon                                             2
2 Bedroom House for sale in Narsinghpur                                                   2
4 Bedroom House for sale in Sector 72 Gurgaon                                             2
4 Bedroom House for sale in Sector 23 Gurgaon                                             2
12 Bedroom House for sale in Sector 40 Gurgaon                                            2
9 Bedroom House for sale in Sector 47 Gurgaon                                             2
4 Bedroom House for sale in Sector 4 Gurgaon                                              2
2 Bedroom House for sale in Sector 70A Gurgaon                                            2
16 Bedroom House for sale in DLF Phase 4                                                  2
3 Bedroom House for sale in Bissar                                                        2
9 Bedroom House for sale in Sector 38 Gurgaon                                             2
9 Bedroom House for sale in Sector 9 Gurgaon                                              2
12 Bedroom House for sale in Sushant Lok Phase 1                                          2
3 Bedroom House for sale in Sector 26 Gurgaon                                             2
5 Bedroom House for sale in Sector 70A Gurgaon                                            2
5 Bedroom House for sale in B Block Sushant Lok Phase 1                                   2
6 Bedroom House for sale in Sushant Lok Phase 1                                           2
3 Bedroom House for sale in Hira Nagar                                                    2
3 Bedroom House for sale in Sushant Lok Phase 2                                           2
2 Bedroom House for sale in Sector-33 Sohna                                               2
9 Bedroom House for sale in Sector 45 Gurgaon                                             2
2 Bedroom House for sale in Daulatabad                                                    2
3 Bedroom House for sale in Sector 23A Gurgaon                                            2
3 Bedroom House for sale in Sector 63A Gurgaon                                            2
4 Bedroom House for sale in Sector 65 Gurgaon                                             2
3 Bedroom House for sale in Devilal Colony                                                2
2 Bedroom House for sale in Sector 5 Gurgaon                                              2
5 Bedroom House for sale in Sector 3 Gurgaon                                              2
2 Bedroom House for sale in Sohna                                                         2
4 Bedroom House for sale in Laxman Vihar Phase 2                                          2
6 Bedroom House for sale in Sector 50 Gurgaon                                             2
1 Bedroom House for sale in Laxman Vihar                                                  2
9 Bedroom House for sale in Palam Vihar Extension                                         2
5 Bedroom House for sale in Sector 5 Gurgaon                                              2
8 Bedroom House for sale in Sector 56 Gurgaon                                             2
2 Bedroom House for sale in Vishnu Garden                                                 2
2 Bedroom House for sale in Sohna Road                                                    2
5 Bedroom House for sale in Sector 11 Gurgaon                                             2
2 Bedroom House for sale in Rajendra Park                                                 2
5 Bedroom House for sale in Sector 7 Gurgaon                                              2
4 Bedroom House for sale in Jacobpura                                                     2
5 Bedroom House for sale in DLF Phase 3                                                   2
6 Bedroom House for sale in Sector 67 Gurgaon                                             2
3 Bedroom House for sale in DLF Phase 1                                                   2
4 Bedroom House for sale in Sector-33 Sohna                                               2
19 Bedroom House for sale in Sector 17A Gurgaon                                           2
4 Bedroom House for sale in Sector 56 Gurgaon                                             2
6 Bedroom House for sale in Sector 38 Gurgaon                                             2
12 Bedroom House for sale in Sector 46 Gurgaon                                            2
5 Bedroom House for sale in Sohna Road                                                    2
7 Bedroom House for sale in DLF Phase 3                                                   2
2 Bedroom House for sale in Sheetla Colony                                                2
3 Bedroom House for sale in Baldev Nagar                                                  2
5 Bedroom House for sale in Sector 53 Gurgaon                                             2
6 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sector 31 Gurgaon                                             2
10 Bedroom House for sale in Shivpuri                                                     2
2 Bedroom House for sale in Garhi Harsaru                                                 2
3 Bedroom House for sale in DLF Phase 2                                                   2
3 Bedroom House for sale in Arjun Nagar                                                   2
2 Bedroom House for sale in Baldev Nagar                                                  2
4 Bedroom House for sale in Arjun Nagar                                                   2
4 Bedroom House for sale in Sector 6 Gurgaon                                              2
4 Bedroom House for sale in Sector 3 Gurgaon                                              2
9 Bedroom House for sale in Palam Vihar                                                   2
5 Bedroom House for sale in Sector 39 Gurgaon                                             2
4 Bedroom House for sale in Rajendra Park                                                 2
3 Bedroom House for sale in Sushant Lok Phase 3                                           2
2 Bedroom House for sale in Devilal Colony                                                2
5 Bedroom House for sale in Ashok Vihar Phase 2                                           2
5 Bedroom House for sale in Sector 108 Gurgaon                                            2
3 Bedroom House for sale in Dharam Colony                                                 2
4 Bedroom House for sale in Saraswati Vihar                                               2
2 Bedroom House for sale in Sector 8 Gurgaon                                              2
1 Bedroom House for sale in Mianwali Colony                                               2
4 Bedroom House for sale in Laxman Vihar                                                  2
5 Bedroom House for sale in Bhim Nagar                                                    2
12 Bedroom House for sale in Malibu Town                                                  2
9 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
1 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 2
7 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sector 56 Gurgaon                                             2
2 Bedroom House for sale in Sector 7 Gurgaon                                              2
4 Bedroom House for sale in Sector 67 Gurgaon                                             2
9 Bedroom House for sale in Sector 40 Gurgaon                                             2
10 Bedroom House for sale in DLF Phase 3                                                  2
7 Bedroom House for sale in DLF Phase 1                                                   2
6 Bedroom House for sale in Sector 14 Gurgaon                                             2
6 Bedroom House for sale in DLF Phase 4                                                   2
6 Bedroom House for sale in New Palam Vihar Phase 1                                       1
13 Bedroom House for sale in DLF Phase 3                                                  1
8 Bedroom House for sale in Sector 17 Gurgaon                                             1
16 Bedroom House for sale in Sushant Lok Phase 1                                          1
16 Bedroom House for sale in Sector 56 Gurgaon                                            1
4 Bedroom House for sale in Sector 33 Gurgaon                                             1
5 Bedroom House for sale in Sector 27 Gurgaon                                             1
16 Bedroom House for sale in DLF Phase 2                                                  1
12 Bedroom House for sale in Sector 27 Gurgaon                                            1
5 Bedroom House for sale in Sector 31 Gurgaon                                             1
4 Bedroom House for sale in Suncity                                                       1
7 Bedroom House for sale in Sector 23 Gurgaon                                             1
9 Bedroom House for sale in A Block Sushant Lok Phase 1                                   1
18 Bedroom House for sale in Suncity                                                      1
5 Bedroom House for sale in Sector 23 Gurgaon                                             1
5 Bedroom House for sale in A Block Sushant Lok Phase 1                                   1
16 Bedroom House for sale in Sector 40 Gurgaon                                            1
4 Bedroom House for sale in Sector 42 Gurgaon                                             1
3 Bedroom House for sale in B Block Sushant Lok Phase 1                                   1
3 Bedroom House for sale in Sector 105 Gurgaon                                            1
4 Bedroom House for sale in Part 3 Sector 5 Gurgaon                                       1
1 Bedroom House for sale in Sohna                                                         1
4 Bedroom House for sale in Sector 63 Gurgaon                                             1
7 Bedroom House for sale in Lucknow                                                       1
4 Bedroom House for sale in Pataudi Road                                                  1
8 Bedroom House for sale in Surya Vihar                                                   1
5 Bedroom House for sale in Khandsa                                                       1
5 Bedroom House for sale in Ravi Nagar                                                    1
3 Bedroom House for sale in Maruti Kunj                                                   1

In [146]:
df['property_name'].str.strip().str.split(' ')

0       [5, Bedroom, House, for, sale, in, Sector, 70A...
1       [5, Bedroom, House, for, sale, in, Sector, 21A...
2       [10, Bedroom, House, for, sale, in, Sushant, L...
3       [21, Bedroom, House, for, sale, in, Sector, 54...
4       [12, Bedroom, House, for, sale, in, Sushant, L...
5       [20, Bedroom, House, for, sale, in, Sushant, L...
6       [5, Bedroom, House, for, sale, in, Sector, 66,...
7       [16, Bedroom, House, for, sale, in, DLF, Phase...
8       [6, Bedroom, House, for, sale, in, DLF, Phase, 2]
9       [3, Bedroom, House, for, sale, in, Sushant, Lo...
10      [4, Bedroom, House, for, sale, in, DLF, Phase, 2]
11      [6, Bedroom, House, for, sale, in, DLF, Phase, 4]
12      [13, Bedroom, House, for, sale, in, DLF, Phase...
13      [5, Bedroom, House, for, sale, in, DLF, Phase, 1]
14      [5, Bedroom, House, for, sale, in, B, Block, S...
15      [6, Bedroom, House, for, sale, in, New, Palam,...
16      [9, Bedroom, House, for, sale, in, DLF, Phase, 2]
17      [7, Bedroom, House, for, sale, in, Sector, 38,...
18      [4, Bedroom, House, for, sale, in, Nirvana, Co...
19      [6, Bedroom, House, for, sale, in, Uppals, Sou...
20      [9, Bedroom, House, for, sale, in, Sector, 9, ...
21      [5, Bedroom, House, for, sale, in, Sector, 66,...
22      [4, Bedroom, House, for, sale, in, Sector, 48,...
23      [4, Bedroom, House, for, sale, in, Sector, 48,...
24      [9, Bedroom, House, for, sale, in, DLF, Phase, 2]
25      [5, Bedroom, House, for, sale, in, Sushant, Lo...
26      [5, Bedroom, House, for, sale, in, Sector, 4, ...
27      [9, Bedroom, House, for, sale, in, Sector, 9, ...
28      [9, Bedroom, House, for, sale, in, Sector, 40,...
29      [5, Bedroom, House, for, sale, in, Nirvana, Co...
30      [4, Bedroom, House, for, sale, in, Sector, 67,...
31      [5, Bedroom, House, for, sale, in, DLF, Phase, 2]
32      [10, Bedroom, House, for, sale, in, DLF, Phase...
33      [4, Bedroom, House, for, sale, in, Hsiidc, Plo...
34      [2, Bedroom, House, for, sale, in, Sector, 7, ...
35      [4, Bedroom, House, for, sale, in, Sushant, Lo...
36      [12, Bedroom, House, for, sale, in, DLF, Phase...
37      [3, Bedroom, House, for, sale, in, Sector, 15,...
38      [4, Bedroom, House, for, sale, in, Sector, 28,...
39      [5, Bedroom, House, for, sale, in, DLF, Phase, 2]
40      [5, Bedroom, House, for, sale, in, DLF, Phase, 1]
41        [2, Bedroom, House, for, sale, in, Narsinghpur]
42      [12, Bedroom, House, for, sale, in, Sector, 55...
43      [16, Bedroom, House, for, sale, in, Sushant, L...
44      [12, Bedroom, House, for, sale, in, Sector, 56...
45      [16, Bedroom, House, for, sale, in, Sector, 56...
46      [5, Bedroom, House, for, sale, in, DLF, Phase, 2]
47      [5, Bedroom, House, for, sale, in, Sector, 66,...
48      [4, Bedroom, House, for, sale, in, Sector, 70A...
49      [4, Bedroom, House, for, sale, in, C, Block, S...
50       [3, Bedroom, House, for, sale, in, Palam, Vihar]
51       [8, Bedroom, House, for, sale, in, Palam, Vihar]
52      [5, Bedroom, House, for, sale, in, Greenwood, ...
53      [4, Bedroom, House, for, sale, in, Sector, 112...
54      [6, Bedroom, House, for, sale, in, Uppals, Sou...
55      [3, Bedroom, House, for, sale, in, Sector, 48,...
56      [4, Bedroom, House, for, sale, in, Sector, 48,...
57      [4, Bedroom, House, for, sale, in, Sector, 55,...
58      [4, Bedroom, House, for, sale, in, Sector, 91,...
59      [4, Bedroom, House, for, sale, in, Sector, 86,...
60      [5, Bedroom, House, for, sale, in, Sector, 111...
61      [3, Bedroom, House, for, sale, in, Sector, 40,...
62      [5, Bedroom, House, for, sale, in, Sector, 109...
63      [4, Bedroom, House, for, sale, in, Sector, 109...
64      [5, Bedroom, House, for, sale, in, Sector, 14,...
65      [5, Bedroom, House, for, sale, in, C, Block, S...
66      [5, Bedroom, House, for, sale, in, Sector, 66,...
67      [4, Bedroom, House, for, sale, in, Sector, 66,...
68      [5, Bedroom, House, for, sale, in, Sector, 109...
69      [4, Bedroom, House, for, sale, in, Sector, 109...
70      [3, Bedroom, House, for, sale, in, Sector, 109...
71      [4, Bedroom, House, for, sale, in, Sector, 112...
72      [4, Bedroom, House, for, sale, in, Sector, 66,...
73      [5, Bedroom, House, for, sale, in, Sector, 66,...
74      [4, Bedroom, House, for, sale, in, Sector, 66,...
75      [3, Bedroom, House, for, sale, in, Sector, 73,...
76      [5, Bedroom, House, for, sale, in, Sector, 109...
77      [4, Bedroom, House, for, sale, in, Sector, 109...
78      [3, Bedroom, House, for, sale, in, Sector, 109...
79      [12, Bedroom, House, for, sale, in, Sector, 40...
80      [4, Bedroom, House, for, sale, in, Sector, 23,...
81      [5, Bedroom, House, for, sale, in, Sector, 66,...
82      [4, Bedroom, House, for, sale, in, Sector, 66,...
83      [4, Bedroom, House, for, sale, in, Sector, 109...
84      [3, Bedroom, House, for, sale, in, Sector, 109...
85      [4, Bedroom, House, for, sale, in, Sector, 23,...
86      [4, Bedroom, House, for, sale, in, Sector, 72,...
87      [4, Bedroom, House, for, sale, in, Sector, 112...
88      [5, Bedroom, House, for, sale, in, Sector, 63A...
89      [3, Bedroom, House, for, sale, in, Sector, 63A...
90      [4, Bedroom, House, for, sale, in, Sector, 109...
91      [4, Bedroom, House, for, sale, in, Sector, 109...
92      [4, Bedroom, House, for, sale, in, Sector, 48,...
93      [3, Bedroom, House, for, sale, in, Sector, 48,...
94      [5, Bedroom, House, for, sale, in, Sector, 48,...
95      [4, Bedroom, House, for, sale, in, Sector, 48,...
96      [3, Bedroom, House, for, sale, in, Sector, 48,...
97      [3, Bedroom, House, for, sale, in, Sector, 73,...
98      [5, Bedroom, House, for, sale, in, Sector, 48,...
99      [4, Bedroom, House, for, sale, in, Sector, 48,...
100     [3, Bedroom, House, for, sale, in, Sector, 48,...
101     [4, Bedroom, House, for, sale, in, Sector, 66,...
102     [5, Bedroom, House, for, sale, in, Sector, 66,...
103     [4, Bedroom, House, for, sale, in, Sector, 66,...
104     [4, Bedroom, House, for, sale, in, Sector, 65,...
105     [4, Bedroom, House, for, sale, in, Sector-33, ...
106     [3, Bedroom, House, for, sale, in, Sector, 4, ...
107     [3, Bedroom, House, for, sale, in, Sector, 4, ...
108     [4, Bedroom, House, for, sale, in, Nirvana, Co...
109     [5, Bedroom, House, for, sale, in, Sector, 48,...
110     [5, Bedroom, House, for, sale, in, Sector, 111...
111     [5, Bedroom, House, for, sale, in, Sector, 111...
112     [5, Bedroom, House, for, sale, in, Sector, 82,...
113     [3, Bedroom, House, for, sale, in, Laxman, Vih...
114     [4, Bedroom, House, for, sale, in, Sector, 109...
115     [3, Bedroom, House, for, sale, in, Sector, 73,...
116     [4, Bedroom, House, for, sale, in, Sector, 109...
117     [3, Bedroom, House, for, sale, in, Sector, 9, ...
118     [12, Bedroom, House, for, sale, in, Sector, 56...
119     [4, Bedroom, House, for, sale, in, Sector, 48,...
120     [4, Bedroom, House, for, sale, in, Sector, 82,...
121       [2, Bedroom, House, for, sale, in, New, Colony]
122     [4, Bedroom, House, for, sale, in, Sector, 7, ...
123     [2, Bedroom, House, for, sale, in, Sector, 7, ...
124     [3, Bedroom, House, for, sale, in, Sector, 7, ...
125     [3, Bedroom, House, for, sale, in, Sector, 7, ...
126     [4, Bedroom, House, for, sale, in, Nirvana, Co...
127     [4, Bedroom, House, for, sale, in, Sector, 48,...
128     [4, Bedroom, House, for, sale, in, Sector, 66,...
129     [5, Bedroom, House, for, sale, in, Sector, 109...
130     [4, Bedroom, House, for, sale, in, Sector, 109...
131     [7, Bedroom, House, for, sale, in, Sector, 109...
132     [5, Bedroom, House, for, sale, in, Sector, 109...
133     [5, Bedroom, House, for, sale, in, Sector, 109...
134     [5, Bedroom, House, for, sale, in, Sector, 56,...
135     [5, Bedroom, House, for, sale, in, Sector, 17C...
136     [4, Bedroom, House, for, sale, in, Sector, 109...
137     [4, Bedroom, House, for, sale, in, Sector, 109...
138     [4, Bedroom, House, for, sale, in, Sector, 70A...
139     [4, Bedroom, House, for, sale, in, Sector, 70A...
140     [6, Bedroom, House, for, sale, in, DLF, Phase, 2]
141     [4, Bedroom, House, for, sale, in, Sector, 109...
142     [5, Bedroom, House, for, sale, in, Sector, 109...
143     [3, Bedroom, House, for, sale, in, Rajendra, P...
144     [3, Bedroom, House, for, sale, in, Laxman, Vih...
145     [3, Bedroom, House, for, sale, in, Laxman, Vih...
146     [2, Bedroom, House, for, sale, in, Laxman, Vih...
147     [1, Bedroom, House, for, sale, in, Laxman, Vih...
148     [2, Bedroom, House, for, sale, in, Laxman, Vih...
149     [3, Bedroom, House, for, sale, in, Laxman, Vih...
150     [6, Bedroom, House, for, sale, in, Sushant, Lo...
151     [4, Bedroom, House, for, sale, in, Sector, 109...
152     [9, Bedroom, House, for, sale, in, Sector, 57,...
153     [18, Bedroom, House, for, sale, in, Sector, 55...
154     [16, Bedroom, House, for, sale, in, Shivaji, N...
155     [4, Bedroom, House, for, sale, in, Sector, 31,...
156     [7, Bedroom, House, for, sale, in, Sushant, Lo...
157     [1, Bedroom, House, for, sale, in, Sushant, Lo...
158     [4, Bedroom, House, for, sale, in, Nirvana, Co...
159     [3, Bedroom, House, for, sale, in, Nirvana, Co...
160      [5, Bedroom, House, for, sale, in, Palam, Vihar]
161     [7, Bedroom, House, for, sale, in, Sector, 109...
162     [7, Bedroom, House, for, sale, in, Sector, 109...
163     [4, Bedroom, House, for, sale, in, Sector, 70A...
164     [4, Bedroom, House, for, sale, in, Sector, 109...
165     [9, Bedroom, House, for, sale, in, Dharam, Col...
166     [3, Bedroom, House, for, sale, in, Krishna, Co...
167     [3, Bedroom, House, for, sale, in, Laxman, Vihar]
168     [3, Bedroom, House, for, sale, in, DLF, Phase, 3]
169     [4, Bedroom, House, for, sale, in, Ashok, Viha...
170     [9, Bedroom, House, for, sale, in, Sector, 9A,...
171     [3, Bedroom, House, for, sale, in, Sector, 3, ...
172       [3, Bedroom, House, for, sale, in, Hira, Nagar]
173     [4, Bedroom, House, for, sale, in, Gopal, Naga...
174     [5, Bedroom, House, for, sale, in, Jat, Colony...
175     [7, Bedroom, House, for, sale, in, South, City...
176     [19, Bedroom, House, for, sale, in, Sector, 17...
177     [4, Bedroom, House, for, sale, in, Sector, 56,...
178             [2, Bedroom, House, for, sale, in, Kheri]
179         [6, Bedroom, House, for, sale, in, Madanpuri]
180     [7, Bedroom, House, for, sale, in, DLF, Phase, 3]
181       [5, Bedroom, House, for, sale, in, Sohna, Road]
182     [3, Bedroom, House, for, sale, in, Dayanand, C...
183      [2, Bedroom, House, for, sale, in, Mohan, Nagar]
184     [3, Bedroom, House, for, sale, in, Rajendra, P...
185        [2, Bedroom, House, for, sale, in, Daulatabad]
186     [5, Bedroom, House, for, sale, in, Ashok, Viha...
187     [2, Bedroom, House, for, sale, in, Vishnu, Gar...
188     [4, Bedroom, House, for, sale, in, DLF, Phase, 1]
189        [8, Bedroom, House, for, sale, in, New, Basti]
190     [4, Bedroom, House, for, sale, in, Shivaji, Na...
191           [8, Bedroom, House, for, sale, in, Manesar]
192       [4, Bedroom, House, for, sale, in, New, Colony]
193     [4, Bedroom, House, for, sale, in, Sector, 8, ...
194      [3, Bedroom, House, for, sale, in, Ashok, Vihar]
195      [4, Bedroom, House, for, sale, in, Maruti, Kunj]
196     [5, Bedroom, House, for, sale, in, Laxmi, Garden]
197      [4, Bedroom, House, for, sale, in, Mohan, Nagar]
198     [1, Bedroom, House, for, sale, in, Sector, 9B,...
199     [6, Bedroom, House, for, sale, in, Saraswati, ...
200      [8, Bedroom, House, for, sale, in, IMT, Manesar]
201      [2, Bedroom, House, for, sale, in, Bhora, Kalan]
202     [9, Bedroom, House, for, sale, in, near, nand,...
203     [8, Bedroom, House, for, sale, in, DLF, Phase, 1]
204         [10, Bedroom, House, for, sale, in, Shivpuri]
205     [4, Bedroom, House, for, sale, in, Sector, 92,...
206     [4, Bedroom, House, for, sale, in, Sector, 76,...
207     [5, Bedroom, House, for, sale, in, Sector, 72,...
208       [5, Bedroom, House, for, sale, in, Jyoti, Park]
209             [3, Bedroom, House, for, sale, in, Sohna]
210     [4, Bedroom, House, for, sale, in, Subhash, Na...
211     [2, Bedroom, House, for, sale, in, New, Palam,...
212      [6, Bedroom, House, for, sale, in, Palam, Vihar]
213     [2, Bedroom, House, for, sale, in, Surat, Naga...
214     [3, Bedroom, House, for, sale, in, Sector, 14,...
215     [5, Bedroom, House, for, sale, in, Sector, 33,...
216     [8, Bedroom, House, for, sale, in, Sector, 56,...
217      [3, Bedroom, House, for, sale, in, Ashok, Vihar]
218     [3, Bedroom, House, for, sale, in, Sector, 93,...
219     [5, Bedroom, House, for, sale, in, Sector, 5, ...
220     [4, Bedroom, House, for, sale, in, Rajendra, P...
221     [10, Bedroom, House, for, sale, in, Rajiv, Nagar]
222         [5, Bedroom, House, for, sale, in, Madanpuri]
223     [3, Bedroom, House, for, sale, in, New, Palam,...
224      [6, Bedroom, House, for, sale, in, Arjun, Nagar]
225     [4, Bedroom, House, for, sale, in, Ashok, Viha...
226     [2, Bedroom, House, for, sale, in, Sector, 5, ...
227      [5, Bedroom, House, for, sale, in, Surya, Vihar]
228     [6, Bedroom, House, for, sale, in, Block, H, A...
229     [5, Bedroom, House, for, sale, in, DLF, Phase, 1]
230     [3, Bedroom, House, for, sale, in, Devilal, Co...
231     [10, Bedroom, House, for, sale, in, Sector, 38...
232      [3, Bedroom, House, for, sale, in, Surya, Vihar]
233       [6, Bedroom, House, for, sale, in, Prem, Nagar]
234       [6, Bedroom, House, for, sale, in, Bhim, Nagar]
235     [2, Bedroom, House, for, sale, in, Laxman, Vih...
236      [7, Bedroom, House, for, sale, in, Surat, Nagar]
237     [5, Bedroom, House, for, sale, in, Gandhi, Nagar]
238           [5, Bedroom, House, for, sale, in, Khandsa]
239     [3, Bedroom, House, for, sale, in, Sector, 109...
240     [1, Bedroom, House, for, sale, in, Ashok, Viha...
241       [5, Bedroom, House, for, sale, in, Ravi, Nagar]
242      [3, Bedroom, House, for, sale, in, Maruti, Kunj]
243     [7, Bedroom, House, for, sale, in, Rajendra, P...
244     [5, Bedroom, House, for, sale, in, Sector, 50,...
245     [4, Bedroom, House, for, sale, in, URBAN, ESTA...
246     [3, Bedroom, House, for, sale, in, New, Palam,...
247     [36, Bedroom, House, for, sale, in, West, Raji...
248     [2, Bedroom, House, for, sale, in, Ashok, Viha...
249     [6, Bedroom, House, for, sale, in, Surat, Naga...
250     [6, Bedroom, House, for, sale, in, Sector, 11,...
251     [5, Bedroom, House, for, sale, in, Vishnu, Gar...
252     [3, Bedroom, House, for, sale, in, Sushant, Lo...
253     [4, Bedroom, House, for, sale, in, Near, Khand...
254     [2, Bedroom, House, for, sale, in, Devilal, Co...
255     [9, Bedroom, House, for, sale, in, Sheetla, Co...
256     [5, Bedroom, House, for, sale, in, Laxman, Vihar]
257       [6, Bedroom, House, for, sale, in, Farukhnagar]
258      [10, Bedroom, House, for, sale, in, Ravi, Nagar]
259     [1, Bedroom, House, for, sale, in, Mianwali, C...
260     [2, Bedroom, House, for, sale, in, Sector, 8, ...
261     [3, Bedroom, House, for, sale, in, Dharam, Col...
262      [4, Bedroom, House, for, sale, in, Palam, Vihar]
263     [4, Bedroom, House, for, sale, in, Sector, 55,...
264     [4, Bedroom, House, for, sale, in, Part, 3, Se...
265             [1, Bedroom, House, for, sale, in, Sohna]
266     [3, Bedroom, House, for, sale, in, Sector, 38,...
267     [4, Bedroom, House, for, sale, in, Saraswati, ...
268     [4, Bedroom, House, for, sale, in, Sector, 63,...
269           [7, Bedroom, House, for, sale, in, Lucknow]
270     [4, Bedroom, House, for, sale, in, Pataudi, Road]
271      [8, Bedroom, House, for, sale, in, Surya, Vihar]
272       [4, Bedroom, House, for, sale, in, Ravi, Nagar]
273     [5, Bedroom, House, for, sale, in, Sector, 81,...
274     [9, Bedroom, House, for, sale, in, Subhash, Na...
275     [3, Bedroom, House, for, sale, in, Sector, 38,...
276     [2, Bedroom, House, for, sale, in, Sector, 56,...
277     [4, Bedroom, House, for, sale, in, Sector-33, ...
278     [6, Bedroom, House, for, sale, in, Sector, 70,...
279     [3, Bedroom, House, for, sale, in, Sector, 105...
280       [5, Bedroom, House, for, sale, in, Jyoti, Park]
281     [6, Bedroom, House, for, sale, in, DLF, Phase, 2]
282     [12, Bedroom, House, for, sale, in, Malibu, Town]
283     [5, Bedroom, House, for, sale, in, Sector, 28,...
284     [3, Bedroom, House, for, sale, in, Sector, 66,...
285     [9, Bedroom, House, for, sale, in, C, Block, S...
286       [5, Bedroom, House, for, sale, in, Bhim, Nagar]
287       [4, Bedroom, House, for, sale, in, Jyoti, Park]
288     [6, Bedroom, House, for, sale, in, Nirvana, Co...
289     [9, Bedroom, House, for, sale, in, Sector, 12,...
290     [5, Bedroom, House, for, sale, in, Laxman, Vihar]
291     [3, Bedroom, House, for, sale, in, Laxman, Vihar]
292     [5, Bedroom, House, for, sale, in, Sector, 109...
293     [4, Bedroom, House, for, sale, in, Sector, 109...
294     [5, Bedroom, House, for, sale, in, Sector, 109...
295     [4, Bedroom, House, for, sale, in, Sector, 109...
296     [3, Bedroom, House, for, sale, in, Sector, 109...
297     [4, Bedroom, House, for, sale, in, Laxman, Vihar]
298     [6, Bedroom, House, for, sale, in, Laxman, Vihar]
299     [2, Bedroom, House, for, sale, in, Shakti, Nagar]
300     [5, Bedroom, House, for, sale, in, Sector, 37D...
301     [2, Bedroom, House, for, sale, in, Baldev, Nagar]
302          [2, Bedroom, House, for, sale, in, Shivpuri]
303        [4, Bedroom, House, for, sale, in, New, Basti]
304     [10, Bedroom, House, for, sale, in, Sector, 56...
305      [1, Bedroom, House, for, sale, in, Rajiv, Nagar]
306     [2, Bedroom, House, for, sale, in, Vishnu, Gar...
307     [6, Bedroom, House, for, sale, in, Acharya, Puri]
308          [10, Bedroom, House, for, sale, in, Bhondsi]
309     [2, Bedroom, House, for, sale, in, Sector, 105...
310      [3, Bedroom, House, for, sale, in, Arjun, Nagar]
311     [3, Bedroom, House, for, sale, in, DLF, Phase, 2]
312     [4, Bedroom, House, for, sale, in, Sector, 92,...
313     [4, Bedroom, House, for, sale, in, Sector, 108...
314     [2, Bedroom, House, for, sale, in, Ashok, Viha...
315     [6, Bedroom, House, for, sale, in, Ashok, Viha...
316     [3, Bedroom, House, for, sale, in, Sector, 109...
317     [2, Bedroom, House, for, sale, in, Garhi, Hars...
318      [3, Bedroom, House, for, sale, in, Arjun, Nagar]
319     [2, Bedroom, House, for, sale, in, Palam, Viha...
320      [2, Bedroom, House, for, sale, in, Rajiv, Nagar]
321      [7, Bedroom, House, for, sale, in, Surya, Vihar]
322     [4, Bedroom, House, for, sale, in, Pratap, Nagar]
323     [34, Bedroom, House, for, sale, in, Manohar, N...
324     [2, Bedroom, House, for, sale, in, Sector, 5, ...
325             [4, Bedroom, House, for, sale, in, Sohna]
326     [4, Bedroom, House, for, sale, in, Sector, 52,...
327     [4, Bedroom, House, for, sale, in, Laxman, Vihar]
328      [4, Bedroom, House, for, sale, in, Arjun, Nagar]
329        [4, Bedroom, House, for, sale, in, Vir, Nagar]
330         [2, Bedroom, House, for, sale, in, Madanpuri]
331     [5, Bedroom, House, for, sale, in, Sector, 82A...
332       [3, Bedroom, House, for, sale, in, Bhim, Nagar]
333     [4, Bedroom, House, for, sale, in, Surat, Naga...
334     [1, Bedroom, House, for, sale, in, Hno, 13, Sa...
335     [2, Bedroom, House, for, sale, in, Sector, 13,...
336     [2, Bedroom, House, for, sale, in, Sector, 17A...
337     [3, Bedroom, House, for, sale, in, New, Palam,...
338       [3, Bedroom, House, for, sale, in, Hira, Nagar]
339     [3, Bedroom, House, for, sale, in, Laxman, Vihar]
340        [4, Bedroom, House, for, sale, in, Ram, Nagar]
341     [3, Bedroom, House, for, sale, in, Baldev, Nagar]
342     [5, Bedroom, House, for, sale, in, Block, G, S...
343     [2, Bedroom, House, for, sale, in, Sheetla, Co...

In [147]:
df['property_type'] = df['property_name'].str.strip().str.split(' ').str.get(2)

C:\Users\vikas\AppData\Local\Temp\ipykernel_13612\4020023999.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['property_type'] = df['property_name'].str.strip().str.split(' ').str.get(2)

In [148]:
df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id,property_type
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724,House
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322,House
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898,House
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164,House
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272,House

In [149]:
df['location'] = df['property_name'].str.strip().str.split('in').str.get(1).str.strip()

C:\Users\vikas\AppData\Local\Temp\ipykernel_13612\953546146.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['location'] = df['property_name'].str.strip().str.split('in').str.get(1).str.strip()

In [150]:
df = df.drop(columns=['link','property_id'])

In [151]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1

In [152]:
df['area'].value_counts()

area
(301 sq.m.) Plot Area            43
(84 sq.m.) Plot Area             37
(251 sq.m.) Plot Area            31
(167 sq.m.) Plot Area            26
(420 sq.m.) Plot Area            24
(226 sq.m.) Plot Area            21
(418 sq.m.) Plot Area            20
(125 sq.m.) Plot Area            19
(201 sq.m.) Plot Area            18
(50 sq.m.) Plot Area             16
(180 sq.m.) Plot Area            16
(135 sq.m.) Plot Area            15
(209 sq.m.) Plot Area            14
(171 sq.m.) Plot Area            12
(42 sq.m.) Plot Area             12
(33 sq.m.) Plot Area             12
(334 sq.m.) Plot Area            11
(293 sq.m.) Plot Area            11
(220 sq.m.) Plot Area            11
(264 sq.m.) Plot Area            10
(51 sq.m.) Plot Area              9
(145 sq.m.) Plot Area             8
(502 sq.m.) Plot Area             8
(151 sq.m.) Plot Area             8
(136 sq.m.) Plot Area             7
(134 sq.m.) Plot Area             7
(161 sq.m.) Plot Area             7
(279 sq.m.) Built-up Area         6
(100 sq.m.) Plot Area             6
(650 sq.m.) Built-up Area         6
(5 sq.m.) Plot Area               6
(836 sq.m.) Plot Area             6
(52 sq.m.) Plot Area              6
(242 sq.m.) Plot Area             6
(350 sq.m.) Plot Area             5
(579 sq.m.) Plot Area             5
(521 sq.m.) Built-up Area         5
(372 sq.m.) Plot Area             5
(6 sq.m.) Plot Area               5
(93 sq.m.) Plot Area              5
(56 sq.m.) Plot Area              5
(42 sq.m.) Built-up Area          5
(84 sq.m.) Carpet Area            5
(93 sq.m.) Built-up Area          5
(286 sq.m.) Plot Area             5
(435 sq.m.) Plot Area             5
(241 sq.m.) Plot Area             4
(54 sq.m.) Plot Area              4
(84 sq.m.) Built-up Area          4
(109 sq.m.) Plot Area             4
(297 sq.m.) Plot Area             4
(217 sq.m.) Plot Area             4
(293 sq.m.) Built-up Area         4
(418 sq.m.) Built-up Area         4
(253 sq.m.) Plot Area             4
(7 sq.m.) Plot Area               4
(125 sq.m.) Built-up Area         3
(37 sq.m.) Plot Area              3
(268 sq.m.) Plot Area             3
(543 sq.m.) Built-up Area         3
(144 sq.m.) Plot Area             3
(28 sq.m.) Plot Area              3
(100 sq.m.) Built-up Area         3
(9 sq.m.) Plot Area               3
(105 sq.m.) Plot Area             3
(14 sq.m.) Plot Area              3
(336 sq.m.) Plot Area             3
(301 sq.m.) Built-up Area         3
(372 sq.m.) Built-up Area         3
(102 sq.m.) Built-up Area         3
(63 sq.m.) Plot Area              3
(158 sq.m.) Plot Area             3
(22 sq.m.) Plot Area              3
(91 sq.m.) Plot Area              3
(139 sq.m.) Plot Area             3
(167 sq.m.) Built-up Area         3
(67 sq.m.) Plot Area              3
(460 sq.m.) Plot Area             3
(99 sq.m.) Plot Area              3
(140 sq.m.) Plot Area             3
(230 sq.m.) Plot Area             3
(98 sq.m.) Plot Area              3
(223 sq.m.) Plot Area             3
(557 sq.m.) Built-up Area         3
(142 sq.m.) Plot Area             3
(107 sq.m.) Plot Area             3
(244 sq.m.) Plot Area             2
(25 sq.m.) Plot Area              2
(73 sq.m.) Plot Area              2
(344 sq.m.) Built-up Area         2
(89 sq.m.) Plot Area              2
(222 sq.m.) Plot Area             2
(299 sq.m.) Plot Area             2
(650 sq.m.) Plot Area             2
(318 sq.m.) Plot Area             2
(186 sq.m.) Built-up Area         2
(44 sq.m.) Plot Area              2
(209 sq.m.) Built-up Area         2
(70 sq.m.) Built-up Area          2
(46 sq.m.) Built-up Area          2
(83 sq.m.) Plot Area              2
(251 sq.m.) Built-up Area         2
(292-358 sq.m.) Built-up Area     2
(468-681 sq.m.) Built-up Area     2
(606 sq.m.) Built-up Area         2
(590-687 sq.m.) Built-up Area     2
(606-754 sq.m.) Built-up Area     2
(232 sq.m.) Carpet Area           2
(467-681 sq.m.) Built-up Area     2
(316 sq.m.) Plot Area             2
(301 sq.m.) Carpet Area           2
(43 sq.m.) Plot Area              2
(121 sq.m.) Built-up Area         2
(166 sq.m.) Plot Area             2
(46 sq.m.) Carpet Area            2
(89 sq.m.) Built-up Area          2
(15 sq.m.) Plot Area              2
(46 sq.m.) Plot Area              2
(113 sq.m.) Plot Area             2
(184 sq.m.) Plot Area             2
(59 sq.m.) Plot Area              2
(132 sq.m.) Built-up Area         2
(85 sq.m.) Plot Area              2
(41 sq.m.) Plot Area              2
(5 sq.m.) Built-up Area           2
(121 sq.m.) Plot Area             2
(76 sq.m.) Built-up Area          2
(88 sq.m.) Plot Area              2
(40 sq.m.) Carpet Area            2
(681 sq.m.) Built-up Area         2
(33 sq.m.) Built-up Area          2
(15 sq.m.) Built-up Area          2
(45 sq.m.) Built-up Area          2
(146 sq.m.) Plot Area             2
(115 sq.m.) Plot Area             2
(232 sq.m.) Plot Area             2
(105 sq.m.) Built-up Area         2
(75 sq.m.) Carpet Area            2
(201 sq.m.) Built-up Area         2
(49 sq.m.) Carpet Area            2
(111 sq.m.) Built-up Area         2
(139 sq.m.) Built-up Area         2
(93 sq.m.) Carpet Area            2
(74 sq.m.) Built-up Area          2
(167 sq.m.) Carpet Area           2
(219 sq.m.) Built-up Area         2
(223 sq.m.) Built-up Area         2
(207 sq.m.) Built-up Area         2
(372-441 sq.m.) Built-up Area     2
(325 sq.m.) Built-up Area         2
(34 sq.m.) Plot Area              2
(353 sq.m.) Built-up Area         2
(149 sq.m.) Built-up Area         2
(376 sq.m.) Plot Area             2
(321 sq.m.) Plot Area             2
(521 sq.m.) Plot Area             2
(135 sq.m.) Carpet Area           2
(110 sq.m.) Carpet Area           2
(108 sq.m.) Plot Area             2
(450 sq.m.) Plot Area             1
(302 sq.m.) Plot Area             1
(128 sq.m.) Plot Area             1
(181 sq.m.) Plot Area             1
(509 sq.m.) Plot Area             1
(159 sq.m.) Plot Area             1
(234 sq.m.) Plot Area             1
(537 sq.m.) Plot Area             1
(754 sq.m.) Plot Area             1
(176 sq.m.) Plot Area             1
(26 sq.m.) Plot Area              1
(189 sq.m.) Plot Area             1
(102 sq.m.) Plot Area             1
(308 sq.m.) Plot Area             1
(669 sq.m.) Plot Area             1
(225 sq.m.) Plot Area             1
(510 sq.m.) Plot Area             1
(155 sq.m.) Plot Area             1
(4699 sq.m.) Plot Area            1
(250 sq.m.) Plot Area             1
(466 sq.m.) Built-up Area         1
(288 sq.m.) Plot Area             1
(314 sq.m.) Plot Area             1
(194 sq.m.) Built-up Area         1
(136 sq.m.) Built-up Area         1
(194 sq.m.) Plot Area             1
(92 sq.m.) Plot Area              1
(465 sq.m.) Plot Area             1
(326 sq.m.) Plot Area             1
(31 sq.m.) Built-up Area          1
(452 sq.m.) Built-up Area         1
(385 sq.m.) Plot Area             1
(540 sq.m.) Built-up Area         1
(363 sq.m.) Built-up Area         1
(92 sq.m.) Built-up Area          1
(177 sq.m.) Plot Area             1
(87 sq.m.) Built-up Area          1
(144 sq.m.) Built-up Area         1
(325 sq.m.) Plot Area             1
(139-279 sq.m.) Built-up Area     1
(650-790 sq.m.) Built-up Area     1
(251-704 sq.m.) Built-up Area     1
(211 sq.m.) Built-up Area         1
(571-711 sq.m.) Built-up Area     1
(293-381 sq.m.) Built-up Area     1
(183 sq.m.) Built-up Area         1
(9 sq.m.) Built-up Area           1
(51 sq.m.) Built-up Area          1
(929 sq.m.) Carpet Area           1
(13 sq.m.) Built-up Area          1
(278 sq.m.) Built-up Area         1
(153 sq.m.) Plot Area             1
(134 sq.m.) Carpet Area           1
(121 sq.m.) Carpet Area           1
(367 sq.m.) Built-up Area         1
(809371 sq.m.) Plot Area          1
(90 sq.m.) Plot Area              1
(19 sq.m.) Plot Area              1
(509-543 sq.m.) Built-up Area     1
(160 sq.m.) Plot Area             1
(697 sq.m.) Built-up Area         1
(7 sq.m.) Built-up Area           1
(233 sq.m.) Built-up Area         1
(478 sq.m.) Built-up Area         1
(57 sq.m.) Plot Area              1
(132 sq.m.) Plot Area             1
(71 sq.m.) Plot Area              1
(95 sq.m.) Plot Area              1
(158 sq.m.) Built-up Area         1
(340 sq.m.) Built-up Area         1
(24 sq.m.) Plot Area              1
(56 sq.m.) Built-up Area          1
(585 sq.m.) Built-up Area         1
(220 sq.m.) Built-up Area         1
(25 sq.m.) Built-up Area          1
(56 sq.m.) Carpet Area            1
(251 sq.m.) Carpet Area           1
(18 sq.m.) Plot Area              1
(325 sq.m.) Carpet Area           1
(23 sq.m.) Carpet Area            1
(291 sq.m.) Plot Area             1
(32 sq.m.) Built-up Area          1
(50 sq.m.) Carpet Area            1
(18 sq.m.) Built-up Area          1
(22 sq.m.) Built-up Area          1
(431 sq.m.) Plot Area             1
(200 sq.m.) Built-up Area         1
(12 sq.m.) Built-up Area          1
(28 sq.m.) Carpet Area            1
(20 sq.m.) Built-up Area          1
(44 sq.m.) Built-up Area          1
(133 sq.m.) Plot Area             1
(246 sq.m.) Plot Area             1
(47 sq.m.) Plot Area              1
(7692 sq.m.) Plot Area            1
(124 sq.m.) Plot Area             1
(163 sq.m.) Built-up Area         1
(49 sq.m.) Plot Area              1
(483 sq.m.) Built-up Area         1
(20064 sq.m.) Plot Area           1
(328 sq.m.) Built-up Area         1
(560 sq.m.) Plot Area             1
(110 sq.m.) Plot Area             1
(151 sq.m.) Carpet Area           1
(76 sq.m.) Plot Area              1
(40 sq.m.) Plot Area              1
(1115 sq.m.) Plot Area            1
(234 sq.m.) Carpet Area           1
(58 sq.m.) Plot Area              1
(65 sq.m.) Plot Area              1
(117 sq.m.) Plot Area             1
(390 sq.m.) Plot Area             1
(74 sq.m.) Plot Area              1
(174 sq.m.) Plot Area             1
(6062 sq.m.) Carpet Area          1
(52 sq.m.) Built-up Area          1
(10 sq.m.) Built-up Area          1
(111 sq.m.) Plot Area             1
(261 sq.m.) Plot Area             1
(260 sq.m.) Carpet Area           1
(339 sq.m.) Plot Area             1
(92 sq.m.) Carpet Area            1
(104 sq.m.) Built-up Area         1
(63 sq.m.) Built-up Area          1
(302 sq.m.) Carpet Area           1
(316 sq.m.) Built-up Area         1
(2415 sq.m.) Plot Area            1
(743 sq.m.) Built-up Area         1
(384-392 sq.m.) Built-up Area     1
(294-418 sq.m.) Built-up Area     1
(188 sq.m.) Built-up Area         1
(5 sq.m.) Carpet Area             1
(117 sq.m.) Built-up Area         1
(98 sq.m.) Built-up Area          1
(135 sq.m.) Built-up Area         1
(242 sq.m.) Built-up Area         1
(291 sq.m.) Carpet Area           1
(124 sq.m.) Built-up Area         1
(204 sq.m.) Plot Area             1
(195 sq.m.) Carpet Area           1
(111 sq.m.) Carpet Area           1
(54 sq.m.) Built-up Area          1
(138 sq.m.) Built-up Area         1
(207 sq.m.) Carpet Area           1
(96 sq.m.) Carpet Area            1
(44 sq.m.) Carpet Area            1
(100 sq.m.) Carpet Area           1
(339 sq.m.) Built-up Area         1
(437 sq.m.) Built-up Area         1
(162 sq.m.) Built-up Area         1
(248 sq.m.) Built-up Area         1
(107 sq.m.) Carpet Area           1
(102 sq.m.) Carpet Area           1
(281 sq.m.) Plot Area             1
(186 sq.m.) Carpet Area           1
(152 sq.m.) Plot Area             1
(66 sq.m.) Plot Area              1
(80 sq.m.) Plot Area              1
(79 sq.m.) Plot Area              1
(176 sq.m.) Built-up Area         1
(143 sq.m.) Built-up Area         1
(69 sq.m.) Plot Area              1
(73 sq.m.) Carpet Area            1
(354 sq.m.) Plot Area             1
(594 sq.m.) Built-up Area         1
(465 sq.m.) Built-up Area         1
(222 sq.m.) Built-up Area         1
(130 sq.m.) Plot Area             1
(60 sq.m.) Plot Area              1
(71 sq.m.) Built-up Area          1
(249 sq.m.) Built-up Area         1
(153 sq.m.) Built-up Area         1
(4 sq.m.) Plot Area               1
(75 sq.m.) Built-up Area          1
(401 sq.m.) Plot Area             1
(1003 sq.m.) Plot Area            1
(21 sq.m.) Plot Area              1
(213 sq.m.) Plot Area             1
(590 sq.m.) Built-up Area         1
(196 sq.m.) Plot Area             1
(585 sq.m.) Plot Area             1
(112 sq.m.) Built-up Area         1
(180 sq.m.) Built-up Area         1
(186 sq.m.) Plot Area             1
(23 sq.m.) Plot Area              1
(1049 sq.m.) Plot Area            1
(283 sq.m.) Plot Area             1
(319 sq.m.) Plot Area             1
(1254 sq.m.) Plot Area            1
(2592 sq.m.) Plot Area            1
(360 sq.m.) Plot Area             1
(511 sq.m.) Built-up Area         1
(13 sq.m.) Plot Area              1
(64 sq.m.) Plot Area              1
(94 sq.m.) Built-up Area          1
(815 sq.m.) Plot Area             1
(254 sq.m.) Plot Area             1
(206 sq.m.) Plot Area             1
(557 sq.m.) Plot Area             1
(743 sq.m.) Plot Area             1
(422 sq.m.) Plot Area             1
(8 sq.m.) Plot Area               1
(543 sq.m.) Plot Area             1
(305 sq.m.) Plot Area             1
(471 sq.m.) Plot Area             1
(210 sq.m.) Plot Area             1
(300 sq.m.) Plot Area             1
(70 sq.m.) Plot Area              1
(255 sq.m.) Plot Area             1
(593 sq.m.) Built-up Area         1
(55 sq.m.) Plot Area              1
(595 sq.m.) Built-up Area         1
(393 sq.m.) Plot Area             1
(190 sq.m.) Plot Area             1
(16 sq.m.) Plot Area              1
(443 sq.m.) Plot Area             1
(12 sq.m.) Plot Area              1
(179 sq.m.) Plot Area             1
(168 sq.m.) Plot Area             1
(149 sq.m.) Plot Area             1
Name: count, dtype: int64

In [153]:
df['area'].str.split(' ')

0               [(242, sq.m.), Plot, Area]
1                [(50, sq.m.), Plot, Area]
2                [(51, sq.m.), Plot, Area]
3               [(108, sq.m.), Plot, Area]
4                [(52, sq.m.), Plot, Area]
5               [(107, sq.m.), Plot, Area]
6               [(301, sq.m.), Plot, Area]
7               [(418, sq.m.), Plot, Area]
8               [(264, sq.m.), Plot, Area]
9               [(180, sq.m.), Plot, Area]
10              [(125, sq.m.), Plot, Area]
11              [(301, sq.m.), Plot, Area]
12              [(136, sq.m.), Plot, Area]
13              [(420, sq.m.), Plot, Area]
14              [(251, sq.m.), Plot, Area]
15              [(125, sq.m.), Plot, Area]
16              [(334, sq.m.), Plot, Area]
17               [(84, sq.m.), Plot, Area]
18              [(201, sq.m.), Plot, Area]
19              [(268, sq.m.), Plot, Area]
20              [(244, sq.m.), Plot, Area]
21              [(293, sq.m.), Plot, Area]
22              [(301, sq.m.), Plot, Area]
23              [(301, sq.m.), Plot, Area]
24              [(180, sq.m.), Plot, Area]
25              [(251, sq.m.), Plot, Area]
26              [(471, sq.m.), Plot, Area]
27              [(242, sq.m.), Plot, Area]
28              [(220, sq.m.), Plot, Area]
29              [(301, sq.m.), Plot, Area]
30              [(210, sq.m.), Plot, Area]
31              [(251, sq.m.), Plot, Area]
32              [(293, sq.m.), Plot, Area]
33               [(84, sq.m.), Plot, Area]
34              [(134, sq.m.), Plot, Area]
35              [(161, sq.m.), Plot, Area]
36              [(251, sq.m.), Plot, Area]
37              [(300, sq.m.), Plot, Area]
38              [(251, sq.m.), Plot, Area]
39              [(251, sq.m.), Plot, Area]
40              [(167, sq.m.), Plot, Area]
41               [(70, sq.m.), Plot, Area]
42              [(251, sq.m.), Plot, Area]
43              [(251, sq.m.), Plot, Area]
44              [(255, sq.m.), Plot, Area]
45              [(251, sq.m.), Plot, Area]
46              [(167, sq.m.), Plot, Area]
47              [(293, sq.m.), Plot, Area]
48              [(242, sq.m.), Plot, Area]
49              [(180, sq.m.), Plot, Area]
50              [(145, sq.m.), Plot, Area]
51              [(301, sq.m.), Plot, Area]
52              [(418, sq.m.), Plot, Area]
53          [(593, sq.m.), Built-up, Area]
54              [(136, sq.m.), Plot, Area]
55              [(241, sq.m.), Plot, Area]
56              [(372, sq.m.), Plot, Area]
57              [(135, sq.m.), Plot, Area]
58              [(316, sq.m.), Plot, Area]
59              [(316, sq.m.), Plot, Area]
60          [(743, sq.m.), Built-up, Area]
61               [(84, sq.m.), Plot, Area]
62      [(467-681, sq.m.), Built-up, Area]
63      [(384-392, sq.m.), Built-up, Area]
64            [(232, sq.m.), Carpet, Area]
65              [(180, sq.m.), Plot, Area]
66      [(606-754, sq.m.), Built-up, Area]
67          [(521, sq.m.), Built-up, Area]
68      [(467-681, sq.m.), Built-up, Area]
69      [(294-418, sq.m.), Built-up, Area]
70          [(293, sq.m.), Built-up, Area]
71      [(590-687, sq.m.), Built-up, Area]
72          [(521, sq.m.), Built-up, Area]
73          [(606, sq.m.), Built-up, Area]
74          [(521, sq.m.), Built-up, Area]
75          [(543, sq.m.), Built-up, Area]
76      [(468-681, sq.m.), Built-up, Area]
77      [(292-358, sq.m.), Built-up, Area]
78          [(293, sq.m.), Built-up, Area]
79              [(220, sq.m.), Plot, Area]
80              [(286, sq.m.), Plot, Area]
81          [(606, sq.m.), Built-up, Area]
82          [(521, sq.m.), Built-up, Area]
83          [(325, sq.m.), Built-up, Area]
84          [(293, sq.m.), Built-up, Area]
85      [(139-279, sq.m.), Built-up, Area]
86      [(650-790, sq.m.), Built-up, Area]
87      [(590-687, sq.m.), Built-up, Area]
88      [(251-704, sq.m.), Built-up, Area]
89          [(211, sq.m.), Built-up, Area]
90              [(226, sq.m.), Plot, Area]
91              [(502, sq.m.), Plot, Area]
92      [(372-441, sq.m.), Built-up, Area]
93          [(279, sq.m.), Built-up, Area]
94      [(571-711, sq.m.), Built-up, Area]
95      [(372-441, sq.m.), Built-up, Area]
96          [(279, sq.m.), Built-up, Area]
97          [(543, sq.m.), Built-up, Area]
98      [(293-381, sq.m.), Built-up, Area]
99          [(207, sq.m.), Built-up, Area]
100         [(301, sq.m.), Built-up, Area]
101         [(223, sq.m.), Built-up, Area]
102     [(606-754, sq.m.), Built-up, Area]
103         [(521, sq.m.), Built-up, Area]
104         [(183, sq.m.), Built-up, Area]
105         [(344, sq.m.), Built-up, Area]
106             [(209, sq.m.), Plot, Area]
107             [(460, sq.m.), Plot, Area]
108             [(251, sq.m.), Plot, Area]
109             [(815, sq.m.), Plot, Area]
110         [(650, sq.m.), Built-up, Area]
111         [(650, sq.m.), Built-up, Area]
112             [(301, sq.m.), Plot, Area]
113              [(73, sq.m.), Plot, Area]
114              [(25, sq.m.), Plot, Area]
115         [(543, sq.m.), Built-up, Area]
116             [(502, sq.m.), Plot, Area]
117             [(220, sq.m.), Plot, Area]
118             [(254, sq.m.), Plot, Area]
119             [(297, sq.m.), Plot, Area]
120             [(301, sq.m.), Plot, Area]
121             [(100, sq.m.), Plot, Area]
122             [(244, sq.m.), Plot, Area]
123             [(134, sq.m.), Plot, Area]
124             [(209, sq.m.), Plot, Area]
125             [(134, sq.m.), Plot, Area]
126             [(223, sq.m.), Plot, Area]
127             [(372, sq.m.), Plot, Area]
128             [(209, sq.m.), Plot, Area]
129             [(418, sq.m.), Plot, Area]
130             [(502, sq.m.), Plot, Area]
131             [(334, sq.m.), Plot, Area]
132             [(502, sq.m.), Plot, Area]
133             [(226, sq.m.), Plot, Area]
134             [(135, sq.m.), Plot, Area]
135             [(161, sq.m.), Plot, Area]
136             [(226, sq.m.), Plot, Area]
137             [(206, sq.m.), Plot, Area]
138             [(557, sq.m.), Plot, Area]
139         [(557, sq.m.), Built-up, Area]
140             [(167, sq.m.), Plot, Area]
141         [(650, sq.m.), Built-up, Area]
142             [(743, sq.m.), Plot, Area]
143              [(67, sq.m.), Plot, Area]
144             [(125, sq.m.), Plot, Area]
145            [(1254, sq.m.), Plot, Area]
146               [(6, sq.m.), Plot, Area]
147               [(7, sq.m.), Plot, Area]
148               [(6, sq.m.), Plot, Area]
149               [(7, sq.m.), Plot, Area]
150             [(180, sq.m.), Plot, Area]
151             [(226, sq.m.), Plot, Area]
152            [(2592, sq.m.), Plot, Area]
153             [(140, sq.m.), Plot, Area]
154             [(167, sq.m.), Plot, Area]
155             [(145, sq.m.), Plot, Area]
156              [(89, sq.m.), Plot, Area]
157             [(180, sq.m.), Plot, Area]
158             [(418, sq.m.), Plot, Area]
159             [(201, sq.m.), Plot, Area]
160             [(360, sq.m.), Plot, Area]
161             [(418, sq.m.), Plot, Area]
162             [(418, sq.m.), Plot, Area]
163         [(511, sq.m.), Built-up, Area]
164             [(502, sq.m.), Plot, Area]
165              [(13, sq.m.), Plot, Area]
166              [(51, sq.m.), Plot, Area]
167              [(64, sq.m.), Plot, Area]
168              [(50, sq.m.), Plot, Area]
169              [(99, sq.m.), Plot, Area]
170             [(293, sq.m.), Plot, Area]
171          [(94, sq.m.), Built-up, Area]
172              [(52, sq.m.), Plot, Area]
173              [(84, sq.m.), Plot, Area]
174              [(98, sq.m.), Plot, Area]
175             [(230, sq.m.), Plot, Area]
176             [(151, sq.m.), Plot, Area]
177             [(140, sq.m.), Plot, Area]
178               [(5, sq.m.), Plot, Area]
179              [(84, sq.m.), Plot, Area]
180         [(279, sq.m.), Built-up, Area]
181              [(63, sq.m.), Plot, Area]
182              [(56, sq.m.), Plot, Area]
183              [(84, sq.m.), Plot, Area]
184          [(42, sq.m.), Built-up, Area]
185               [(7, sq.m.), Plot, Area]
186              [(42, sq.m.), Plot, Area]
187            [(46, sq.m.), Carpet, Area]
188              [(91, sq.m.), Plot, Area]
189              [(22, sq.m.), Plot, Area]
190             [(167, sq.m.), Plot, Area]
191             [(166, sq.m.), Plot, Area]
192             [(334, sq.m.), Plot, Area]
193              [(84, sq.m.), Plot, Area]
194          [(10, sq.m.), Built-up, Area]
195             [(158, sq.m.), Plot, Area]
196         [(121, sq.m.), Built-up, Area]
197             [(139, sq.m.), Plot, Area]
198          [(42, sq.m.), Built-up, Area]
199             [(125, sq.m.), Plot, Area]
200             [(111, sq.m.), Plot, Area]
201              [(63, sq.m.), Plot, Area]
202              [(84, sq.m.), Plot, Area]
203             [(167, sq.m.), Plot, Area]
204             [(209, sq.m.), Plot, Area]
205             [(261, sq.m.), Plot, Area]
206           [(260, sq.m.), Carpet, Area]
207             [(339, sq.m.), Plot, Area]
208            [(92, sq.m.), Carpet, Area]
209         [(104, sq.m.), Built-up, Area]
210          [(63, sq.m.), Built-up, Area]
211              [(25, sq.m.), Plot, Area]
212           [(302, sq.m.), Carpet, Area]
213              [(43, sq.m.), Plot, Area]
214             [(209, sq.m.), Plot, Area]
215             [(418, sq.m.), Plot, Area]
216             [(253, sq.m.), Plot, Area]
217             [(135, sq.m.), Plot, Area]
218             [(107, sq.m.), Plot, Area]
219         [(316, sq.m.), Built-up, Area]
220              [(33, sq.m.), Plot, Area]
221           [(301, sq.m.), Carpet, Area]
222             [(125, sq.m.), Plot, Area]
223              [(84, sq.m.), Plot, Area]
224              [(33, sq.m.), Plot, Area]
225            [(2415, sq.m.), Plot, Area]
226              [(84, sq.m.), Plot, Area]
227             [(125, sq.m.), Plot, Area]
228              [(88, sq.m.), Plot, Area]
229             [(166, sq.m.), Plot, Area]
230          [(76, sq.m.), Built-up, Area]
231          [(32, sq.m.), Built-up, Area]
232            [(50, sq.m.), Carpet, Area]
233          [(18, sq.m.), Built-up, Area]
234          [(22, sq.m.), Built-up, Area]
235             [(431, sq.m.), Plot, Area]
236             [(121, sq.m.), Plot, Area]
237           [(5, sq.m.), Built-up, Area]
238              [(41, sq.m.), Plot, Area]
239         [(200, sq.m.), Built-up, Area]
240          [(93, sq.m.), Built-up, Area]
241          [(42, sq.m.), Built-up, Area]
242              [(52, sq.m.), Plot, Area]
243              [(84, sq.m.), Plot, Area]
244         [(279, sq.m.), Built-up, Area]
245             [(171, sq.m.), Plot, Area]
246             [(372, sq.m.), Plot, Area]
247             [(301, sq.m.), Plot, Area]
248          [(12, sq.m.), Built-up, Area]
249               [(5, sq.m.), Plot, Area]
250             [(251, sq.m.), Plot, Area]
251         [(325, sq.m.), Built-up, Area]
252             [(201, sq.m.), Plot, Area]
253              [(67, sq.m.), Plot, Area]
254            [(28, sq.m.), Carpet, Area]
255          [(20, sq.m.), Built-up, Area]
256          [(44, sq.m.), Built-up, Area]
257              [(84, sq.m.), Plot, Area]
258             [(133, sq.m.), Plot, Area]
259           [(167, sq.m.), Carpet, Area]
260          [(74, sq.m.), Built-up, Area]
261            [(93, sq.m.), Carpet, Area]
262         [(278, sq.m.), Built-up, Area]
263         [(139, sq.m.), Built-up, Area]
264             [(153, sq.m.), Plot, Area]
265              [(28, sq.m.), Plot, Area]
266           [(134, sq.m.), Carpet, Area]
267           [(121, sq.m.), Carpet, Area]
268         [(367, sq.m.), Built-up, Area]
269             [(209, sq.m.), Plot, Area]
270          [(809371, sq.m.), Plot, Area]
271              [(90, sq.m.), Plot, Area]
272              [(19, sq.m.), Plot, Area]
273     [(509-543, sq.m.), Built-up, Area]
274             [(167, sq.m.), Plot, Area]
275             [(160, sq.m.), Plot, Area]
276             [(135, sq.m.), Plot, Area]
277         [(344, sq.m.), Built-up, Area]
278         [(697, sq.m.), Built-up, Area]
279         [(111, sq.m.), Built-up, Area]
280              [(92, sq.m.), Plot, Area]
281         [(557, sq.m.), Built-up, Area]
282         [(149, sq.m.), Built-up, Area]
283             [(465, sq.m.), Plot, Area]
284         [(353, sq.m.), Built-up, Area]
285             [(326, sq.m.), Plot, Area]
286               [(6, sq.m.), Plot, Area]
287          [(31, sq.m.), Built-up, Area]
288         [(452, sq.m.), Built-up, Area]
289             [(385, sq.m.), Plot, Area]
290         [(167, sq.m.), Built-up, Area]
291         [(223, sq.m.), Built-up, Area]
292         [(540, sq.m.), Built-up, Area]
293         [(363, sq.m.), Built-up, Area]
294     [(468-681, sq.m.), Built-up, Area]
295     [(292-358, sq.m.), Built-up, Area]
296         [(293, sq.m.), Built-up, Area]
297              [(33, sq.m.), Plot, Area]
298          [(92, sq.m.), Built-up, Area]
299              [(93, sq.m.), Plot, Area]
300             [(177, sq.m.), Plot, Area]
301          [(84, sq.m.), Built-up, Area]
302             [(167, sq.m.), Plot, Area]
303          [(74, sq.m.), Built-up, Area]
304              [(34, sq.m.), Plot, Area]
305          [(87, sq.m.), Built-up, Area]
306              [(42, sq.m.), Plot, Area]
307         [(144, sq.m.), Built-up, Area]
308             [(325, sq.m.), Plot, Area]
309           [(9, sq.m.), Built-up, Area]
310          [(51, sq.m.), Built-up, Area]
311           [(929, sq.m.), Carpet, Area]
312         [(219, sq.m.), Built-up, Area]
313         [(279, sq.m.), Built-up, Area]
314         [(102, sq.m.), Built-up, Area]
315         [(279, sq.m.), Built-up, Area]
316         [(219, sq.m.), Built-up, Area]
317          [(13, sq.m.), Built-up, Area]
318              [(33, sq.m.), Plot, Area]
319            [(49, sq.m.), Carpet, Area]
320           [(7, sq.m.), Built-up, Area]
321         [(372, sq.m.), Built-up, Area]
322         [(233, sq.m.), Built-up, Area]
323             [(418, sq.m.), Plot, Area]
324          [(93, sq.m.), Built-up, Area]
325             [(167, sq.m.), Plot, Area]
326         [(201, sq.m.), Built-up, Area]
327              [(54, sq.m.), Plot, Area]
328              [(52, sq.m.), Plot, Area]
329            [(75, sq.m.), Carpet, Area]
330              [(42, sq.m.), Plot, Area]
331         [(478, sq.m.), Built-up, Area]
332              [(57, sq.m.), Plot, Area]
333              [(34, sq.m.), Plot, Area]
334              [(89, sq.m.), Plot, Area]
335             [(132, sq.m.), Plot, Area]
336              [(71, sq.m.), Plot, Area]
337             [(100, sq.m.), Plot, Area]
338         [(100, sq.m.), Built-up, Area]
339         [(105, sq.m.), Built-up, Area]
340              [(95, sq.m.), Plot, Area]
341            [(84, sq.m.), Carpet, Area]
342              [(51, sq.m.), Plot, Area]
343              [(84, sq.m.), Plot, Area]
344         [(158, sq.m.), Built-up, Area]
345         [(340, sq.m.), Built-up, Area]
346             [(232, sq.m.), Plot, Area]
347             [(134, sq.m.), Plot, Area]
348         [(650, sq.m.), Built-up, Area]
349             [(226, sq.m.), Plot, Area]
350             [(115, sq.m.), Plot, Area]
351             [(146, sq.m.), Plot, Area]
352             [(109, sq.m.), Plot, Area]
353              [(24, sq.m.), Plot, Area]
354          [(56, sq.m.), Built-up, Area]
355         [(585, sq.m.), Built-up, Area]
356              [(84, sq.m.), Plot, Area]
357             [(167, sq.m.), Plot, Area]
358          [(45, sq.m.), Built-up, Area]
359          [(15, sq.m.), Built-up, Area]
360         [(220, sq.m.), Built-up, Area]
361          [(45, sq.m.), Built-up, Area]
362          [(25, sq.m.), Built-up, Area]
363               [(9, sq.m.), Plot, Area]
364            [(56, sq.m.), Carpet, Area]
365         [(102, sq.m.), Built-up, Area]
366               [(5, sq.m.), Plot, Area]
367              [(50, sq.m.), Plot, Area]
368          [(33, sq.m.), Built-up, Area]
369              [(84, sq.m.), Plot, Area]
370              [(14, sq.m.), Plot, Area]
371         [(681, sq.m.), Built-up, Area]
372           [(251, sq.m.), Carpet, Area]
373             [(301, sq.m.), Plot, Area]
374             [(151, sq.m.), Plot, Area]
375              [(33, sq.m.), Plot, Area]
376              [(18, sq.m.), Plot, Area]
377            [(75, sq.m.), Carpet, Area]
378              [(93, sq.m.), Plot, Area]
379           [(325, sq.m.), Carpet, Area]
380            [(23, sq.m.), Carpet, Area]
381             [(291, sq.m.), Plot, Area]
382              [(84, sq.m.), Plot, Area]
383              [(84, sq.m.), Plot, Area]
384            [(40, sq.m.), Carpet, Area]
385             [(226, sq.m.), Plot, Area]
386             [(246, sq.m.), Plot, Area]
387             [(435, sq.m.), Plot, Area]
388              [(52, sq.m.), Plot, Area]
389             [(460, sq.m.), Plot, Area]
390              [(47, sq.m.), Plot, Area]
391              [(50, sq.m.), Plot, Area]
392               [(5, sq.m.), Plot, Area]
393              [(85, sq.m.), Plot, Area]
394            [(7692, sq.m.), Plot, Area]
395             [(226, sq.m.), Plot, Area]
396              [(33, sq.m.), Plot, Area]
397             [(124, sq.m.), Plot, Area]
398              [(84, sq.m.), Plot, Area]
399         [(132, sq.m.), Built-up, Area]
400            [(93, sq.m.), Carpet, Area]
401         [(301, sq.m.), Built-up, Area]
402              [(73, sq.m.), Plot, Area]
403              [(59, sq.m.), Plot, Area]
404             [(105, sq.m.), Plot, Area]
405               [(7, sq.m.), Plot, Area]
406         [(163, sq.m.), Built-up, Area]
407             [(184, sq.m.), Plot, Area]
408         [(105, sq.m.), Built-up, Area]
409              [(52, sq.m.), Plot, Area]
410             [(293, sq.m.), Plot, Area]
411              [(49, sq.m.), Plot, Area]
412              [(84, sq.m.), Plot, Area]
413             [(113, sq.m.), Plot, Area]
414         [(132, sq.m.), Built-up, Area]
415              [(84, sq.m.), Plot, Area]
416            [(84, sq.m.), Carpet, Area]
417             [(167, sq.m.), Plot, Area]
418             [(136, sq.m.), Plot, Area]
419              [(33, sq.m.), Plot, Area]
420             [(109, sq.m.), Plot, Area]
421            [(40, sq.m.), Carpet, Area]
422         [(483, sq.m.), Built-up, Area]
423              [(42, sq.m.), Plot, Area]
424              [(46, sq.m.), Plot, Area]
425              [(50, sq.m.), Plot, Area]
426           [(20064, sq.m.), Plot, Area]
427              [(56, sq.m.), Plot, Area]
428          [(15, sq.m.), Built-up, Area]
429              [(14, sq.m.), Plot, Area]
430              [(98, sq.m.), Plot, Area]
431         [(328, sq.m.), Built-up, Area]
432             [(336, sq.m.), Plot, Area]
433               [(5, sq.m.), Plot, Area]
434             [(167, sq.m.), Plot, Area]
435              [(84, sq.m.), Plot, Area]
436             [(560, sq.m.), Plot, Area]
437             [(110, sq.m.), Plot, Area]
438             [(167, sq.m.), Plot, Area]
439           [(151, sq.m.), Carpet, Area]
440              [(56, sq.m.), Plot, Area]
441              [(76, sq.m.), Plot, Area]
442              [(15, sq.m.), Plot, Area]
443              [(40, sq.m.), Plot, Area]
444            [(1115, sq.m.), Plot, Area]
445           [(234, sq.m.), Carpet, Area]
446              [(43, sq.m.), Plot, Area]
447              [(42, sq.m.), Plot, Area]
448          [(42, sq.m.), Built-up, Area]
449              [(58, sq.m.), Plot, Area]
450              [(28, sq.m.), Plot, Area]
451              [(56, sq.m.), Plot, Area]
452              [(65, sq.m.), Plot, Area]
453              [(42, sq.m.), Plot, Area]
454             [(372, sq.m.), Plot, Area]
455              [(33, sq.m.), Plot, Area]
456             [(125, sq.m.), Plot, Area]
457             [(121, sq.m.), Plot, Area]
458             [(117, sq.m.), Plot, Area]
459             [(125, sq.m.), Plot, Area]
460              [(84, sq.m.), Plot, Area]
461             [(100, sq.m.), Plot, Area]
462              [(42, sq.m.), Plot, Area]
463              [(50, sq.m.), Plot, Area]
464              [(42, sq.m.), Plot, Area]

In [154]:
df['area_in_sqft'] = round((df['area'].str.split(' ').str.get(0).str.replace('(','').str.strip().str.split('-').str.get(0).astype(float))*(10.764),2)

In [155]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73

In [156]:
df['rate'].value_counts()

rate
₹ 22,222/sq.ft.     14
₹ 11,111/sq.ft.     11
₹ 33,333/sq.ft.     11
₹ 10,000/sq.ft.     10
₹ 30,556/sq.ft.      6
₹ 37,037/sq.ft.      6
₹ 31,481/sq.ft.      6
₹ 13,333/sq.ft.      6
₹ 26,667/sq.ft.      6
₹ 26,235/sq.ft.      6
₹ 23,148/sq.ft.      5
₹ 8,000/sq.ft.       5
₹ 9,444/sq.ft.       5
₹ 23,333/sq.ft.      5
₹ 11,100/sq.ft.      5
₹ 8,889/sq.ft.       5
₹ 5,000/sq.ft.       5
₹ 6,944/sq.ft.       4
₹ 35,000/sq.ft.      4
₹ 18,889/sq.ft.      4
₹ 24,691/sq.ft.      4
₹ 27,778/sq.ft.      4
₹ 21,605/sq.ft.      4
₹ 9,722/sq.ft.       4
₹ 25,000/sq.ft.      4
₹ 32,407/sq.ft.      4
₹ 34,722/sq.ft.      4
₹ 10,556/sq.ft.      3
₹ 36,111/sq.ft.      3
₹ 13,889/sq.ft.      3
₹ 33,951/sq.ft.      3
₹ 15,625/sq.ft.      3
₹ 32,222/sq.ft.      3
₹ 29,880/sq.ft.      3
₹ 8,333/sq.ft.       3
₹ 50,000/sq.ft.      3
₹ 11,250/sq.ft.      3
₹ 7,500/sq.ft.       3
₹ 60,000/sq.ft.      3
₹ 20,000/sq.ft.      3
₹ 25,926/sq.ft.      3
₹ 16,058/sq.ft.      3
₹ 8,235/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 12,000/sq.ft.      3
₹ 8,444/sq.ft.       3
₹ 15,555/sq.ft.      3
₹ 6,666/sq.ft.       3
₹ 12,222/sq.ft.      3
₹ 14,815/sq.ft.      3
₹ 11,852/sq.ft.      2
₹ 10,783/sq.ft.      2
₹ 32,963/sq.ft.      2
₹ 7,407/sq.ft.       2
₹ 24,306/sq.ft.      2
₹ 26,389/sq.ft.      2
₹ 12,963/sq.ft.      2
₹ 38,095/sq.ft.      2
₹ 38,760/sq.ft.      2
₹ 24,845/sq.ft.      2
₹ 21,124/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 10,753/sq.ft.      2
₹ 9,000/sq.ft.       2
₹ 48,148/sq.ft.      2
₹ 4,444/sq.ft.       2
₹ 24,500/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 59,259/sq.ft.      2
₹ 13,622/sq.ft.      2
₹ 3,500/sq.ft.       2
₹ 20,635/sq.ft.      2
₹ 8,888/sq.ft.       2
₹ 3,857/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 21,759/sq.ft.      2
₹ 26,852/sq.ft.      2
₹ 25,562/sq.ft.      2
₹ 75,000/sq.ft.      2
₹ 16,975/sq.ft.      2
₹ 17,037/sq.ft.      2
₹ 14,444/sq.ft.      2
₹ 10,101/sq.ft.      2
₹ 20,833/sq.ft.      2
₹ 12,500/sq.ft.      2
₹ 17,284/sq.ft.      2
₹ 100,000/sq.ft.     2
₹ 15,257/sq.ft.      2
₹ 17,778/sq.ft.      2
₹ 55,000/sq.ft.      2
₹ 13,910/sq.ft.      2
₹ 13,000/sq.ft.      2
₹ 35,185/sq.ft.      2
₹ 12,027/sq.ft.      2
₹ 29,630/sq.ft.      2
₹ 15,700/sq.ft.      2
₹ 19,708/sq.ft.      2
₹ 10,518/sq.ft.      2
₹ 39,841/sq.ft.      2
₹ 37,627/sq.ft.      2
₹ 16,039/sq.ft.      2
₹ 45,833/sq.ft.      2
₹ 12,342/sq.ft.      2
₹ 38,580/sq.ft.      2
₹ 35,556/sq.ft.      2
₹ 44,444/sq.ft.      2
₹ 23,457/sq.ft.      2
₹ 9,634/sq.ft.       2
₹ 24,155/sq.ft.      2
₹ 42,222/sq.ft.      2
₹ 38,194/sq.ft.      2
₹ 32,328/sq.ft.      2
₹ 7,290/sq.ft.       1
₹ 27,741/sq.ft.      1
₹ 43,534/sq.ft.      1
₹ 45,889/sq.ft.      1
₹ 20,690/sq.ft.      1
₹ 29,716/sq.ft.      1
₹ 16,378/sq.ft.      1
₹ 37,777/sq.ft.      1
₹ 12,519/sq.ft.      1
₹ 27,971/sq.ft.      1
₹ 21,000/sq.ft.      1
₹ 13,909/sq.ft.      1
₹ 35,400/sq.ft.      1
₹ 13,623/sq.ft.      1
₹ 13,331/sq.ft.      1
₹ 40,135/sq.ft.      1
₹ 16,244/sq.ft.      1
₹ 16,999/sq.ft.      1
₹ 10,714/sq.ft.      1
₹ 10,463/sq.ft.      1
₹ 18,750/sq.ft.      1
₹ 27,793/sq.ft.      1
₹ 22,006/sq.ft.      1
₹ 28,760/sq.ft.      1
₹ 41,615/sq.ft.      1
₹ 38,703/sq.ft.      1
₹ 12,828/sq.ft.      1
₹ 12,842/sq.ft.      1
₹ 8,557/sq.ft.       1
₹ 16,428/sq.ft.      1
₹ 13,519/sq.ft.      1
₹ 42,032/sq.ft.      1
₹ 24,069/sq.ft.      1
₹ 14,650/sq.ft.      1
₹ 13,778/sq.ft.      1
₹ 21,250/sq.ft.      1
₹ 38,667/sq.ft.      1
₹ 12,593/sq.ft.      1
₹ 25,514/sq.ft.      1
₹ 17,650/sq.ft.      1
₹ 24,280/sq.ft.      1
₹ 26,423/sq.ft.      1
₹ 8,916/sq.ft.       1
₹ 36,667/sq.ft.      1
₹ 9,028/sq.ft.       1
₹ 4,074/sq.ft.       1
₹ 630/sq.ft.         1
₹ 86,567/sq.ft.      1
₹ 92,857/sq.ft.      1
₹ 88,157/sq.ft.      1
₹ 29,974/sq.ft.      1
₹ 2,778/sq.ft.       1
₹ 46,906/sq.ft.      1
₹ 23,699/sq.ft.      1
₹ 25,960/sq.ft.      1
₹ 28,424/sq.ft.      1
₹ 4,490/sq.ft.       1
₹ 14,729/sq.ft.      1
₹ 25,111/sq.ft.      1
₹ 7,309/sq.ft.       1
₹ 74,074/sq.ft.      1
₹ 10,233/sq.ft.      1
₹ 8,878/sq.ft.       1
₹ 14,286/sq.ft.      1
₹ 8,928/sq.ft.       1
₹ 8,007/sq.ft.       1
₹ 5,698/sq.ft.       1
₹ 28,283/sq.ft.      1
₹ 24,214/sq.ft.      1
₹ 26,613/sq.ft.      1
₹ 138,888/sq.ft.     1
₹ 7,666/sq.ft.       1
₹ 4,666/sq.ft.       1
₹ 7,778/sq.ft.       1
₹ 40,775/sq.ft.      1
₹ 99,173/sq.ft.      1
₹ 6,172/sq.ft.       1
₹ 9,111/sq.ft.       1
₹ 80,357/sq.ft.      1
₹ 4,117/sq.ft.       1
₹ 7,308/sq.ft.       1
₹ 8,701/sq.ft.       1
₹ 2,296/sq.ft.       1
₹ 9,793/sq.ft.       1
₹ 6,250/sq.ft.       1
₹ 8,486/sq.ft.       1
₹ 11,717/sq.ft.      1
₹ 7,589/sq.ft.       1
₹ 12,592/sq.ft.      1
₹ 15,384/sq.ft.      1
₹ 7,843/sq.ft.       1
₹ 29,336/sq.ft.      1
₹ 10,288/sq.ft.      1
₹ 11,284/sq.ft.      1
₹ 11,029/sq.ft.      1
₹ 10,277/sq.ft.      1
₹ 8,518/sq.ft.       1
₹ 10,555/sq.ft.      1
₹ 557/sq.ft.         1
₹ 8,947/sq.ft.       1
₹ 39,265/sq.ft.      1
₹ 6,083/sq.ft.       1
₹ 230,547/sq.ft.     1
₹ 8,411/sq.ft.       1
₹ 32,291/sq.ft.      1
₹ 41,666/sq.ft.      1
₹ 7,280/sq.ft.       1
₹ 90,000/sq.ft.      1
₹ 10,089/sq.ft.      1
₹ 8,697/sq.ft.       1
₹ 8,500/sq.ft.       1
₹ 9,333/sq.ft.       1
₹ 21,667/sq.ft.      1
₹ 20,425/sq.ft.      1
₹ 5,472/sq.ft.       1
₹ 57,692/sq.ft.      1
₹ 10,482/sq.ft.      1
₹ 25,386/sq.ft.      1
₹ 8,735/sq.ft.       1
₹ 18,667/sq.ft.      1
₹ 2,525/sq.ft.       1
₹ 17,695/sq.ft.      1
₹ 21,519/sq.ft.      1
₹ 17,817/sq.ft.      1
₹ 2/sq.ft.           1
₹ 6,173/sq.ft.       1
₹ 13,888/sq.ft.      1
₹ 20,323/sq.ft.      1
₹ 20,359/sq.ft.      1
₹ 5,833/sq.ft.       1
₹ 11,693/sq.ft.      1
₹ 53,125/sq.ft.      1
₹ 17,900/sq.ft.      1
₹ 39,886/sq.ft.      1
₹ 126,865/sq.ft.     1
₹ 40,909/sq.ft.      1
₹ 27,155/sq.ft.      1
₹ 14,492/sq.ft.      1
₹ 14,045/sq.ft.      1
₹ 10,804/sq.ft.      1
₹ 14,167/sq.ft.      1
₹ 13,157/sq.ft.      1
₹ 5,888/sq.ft.       1
₹ 7,875/sq.ft.       1
₹ 9,654/sq.ft.       1
₹ 4,808/sq.ft.       1
₹ 8,222/sq.ft.       1
₹ 11,273/sq.ft.      1
₹ 7,627/sq.ft.       1
₹ 5,666/sq.ft.       1
₹ 6,567/sq.ft.       1
₹ 22,068/sq.ft.      1
₹ 66,666/sq.ft.      1
₹ 8,386/sq.ft.       1
₹ 28,674/sq.ft.      1
₹ 9,725/sq.ft.       1
₹ 21,111/sq.ft.      1
₹ 10,784/sq.ft.      1
₹ 12,162/sq.ft.      1
₹ 8,910/sq.ft.       1
₹ 19,869/sq.ft.      1
₹ 8,796/sq.ft.       1
₹ 7,522/sq.ft.       1
₹ 5,658/sq.ft.       1
₹ 24,545/sq.ft.      1
₹ 7,701/sq.ft.       1
₹ 14,072/sq.ft.      1
₹ 26,000/sq.ft.      1
₹ 24,305/sq.ft.      1
₹ 19,286/sq.ft.      1
₹ 22,634/sq.ft.      1
₹ 26,570/sq.ft.      1
₹ 6,410/sq.ft.       1
₹ 133,079/sq.ft.     1
₹ 5,778/sq.ft.       1
₹ 6,111/sq.ft.       1
₹ 78,125/sq.ft.      1
₹ 17,955/sq.ft.      1
₹ 7,916/sq.ft.       1
₹ 211,111/sq.ft.     1
₹ 80,000/sq.ft.      1
₹ 120,000/sq.ft.     1
₹ 22,297/sq.ft.      1
₹ 125,000/sq.ft.     1
₹ 73,333/sq.ft.      1
₹ 6,790/sq.ft.       1
₹ 315,789/sq.ft.     1
₹ 10,224/sq.ft.      1
₹ 3,285/sq.ft.       1
₹ 74,000/sq.ft.      1
₹ 27,139/sq.ft.      1
₹ 23,662/sq.ft.      1
₹ 17,574/sq.ft.      1
₹ 9,091/sq.ft.       1
₹ 23,557/sq.ft.      1
₹ 105,263/sq.ft.     1
₹ 21,195/sq.ft.      1
₹ 151/sq.ft.         1
₹ 25,103/sq.ft.      1
₹ 14,954/sq.ft.      1
₹ 8,784/sq.ft.       1
₹ 6,500/sq.ft.       1
₹ 35,494/sq.ft.      1
₹ 11,464/sq.ft.      1
₹ 11,718/sq.ft.      1
₹ 11,555/sq.ft.      1
₹ 3,874/sq.ft.       1
₹ 7,576/sq.ft.       1
₹ 11,556/sq.ft.      1
₹ 10,378/sq.ft.      1
₹ 11,888/sq.ft.      1
₹ 32,258/sq.ft.      1
₹ 16,389/sq.ft.      1
₹ 31,506/sq.ft.      1
₹ 12,820/sq.ft.      1
₹ 229,885/sq.ft.     1
₹ 12,400/sq.ft.      1
₹ 232/sq.ft.         1
₹ 218,750/sq.ft.     1
₹ 54,794/sq.ft.      1
₹ 14,245/sq.ft.      1
₹ 6,367/sq.ft.       1
₹ 37,313/sq.ft.      1
₹ 90,909/sq.ft.      1
₹ 10,122/sq.ft.      1
₹ 8,642/sq.ft.       1
₹ 6,481/sq.ft.       1
₹ 6,707/sq.ft.       1
₹ 245,398/sq.ft.     1
₹ 11,904/sq.ft.      1
₹ 9,135/sq.ft.       1
₹ 7,111/sq.ft.       1
₹ 8,012/sq.ft.       1
₹ 183,333/sq.ft.     1
₹ 10,142/sq.ft.      1
₹ 8,125/sq.ft.       1
₹ 14,583/sq.ft.      1
₹ 11,538/sq.ft.      1
₹ 8,730/sq.ft.       1
₹ 8,230/sq.ft.       1
₹ 13,095/sq.ft.      1
₹ 29,311/sq.ft.      1
₹ 30,384/sq.ft.      1
₹ 19,818/sq.ft.      1
₹ 1,992/sq.ft.       1
₹ 7,619/sq.ft.       1
₹ 98,214/sq.ft.      1
₹ 13,499/sq.ft.      1
₹ 7,820/sq.ft.       1
₹ 4,000/sq.ft.       1
₹ 14,720/sq.ft.      1
₹ 5,664/sq.ft.       1
₹ 19,753/sq.ft.      1
₹ 76,000/sq.ft.      1
₹ 63,492/sq.ft.      1
₹ 2,500/sq.ft.       1
₹ 6,667/sq.ft.       1
₹ 3,704/sq.ft.       1
₹ 12,777/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 20,233/sq.ft.      1
₹ 20,115/sq.ft.      1
₹ 20,062/sq.ft.      1
₹ 11,494/sq.ft.      1
₹ 25,543/sq.ft.      1
₹ 12,343/sq.ft.      1
₹ 16,892/sq.ft.      1
₹ 17,500/sq.ft.      1
₹ 3,904/sq.ft.       1
₹ 14,323/sq.ft.      1
₹ 4,222/sq.ft.       1
₹ 181,818/sq.ft.     1
₹ 26,620/sq.ft.      1
₹ 9,500/sq.ft.       1
₹ 17,937/sq.ft.      1
₹ 3,254/sq.ft.       1
₹ 5,333/sq.ft.       1
₹ 4,583/sq.ft.       1
₹ 21,875/sq.ft.      1
₹ 16,667/sq.ft.      1
₹ 7,075/sq.ft.       1
₹ 8,078/sq.ft.       1
₹ 4,251/sq.ft.       1
₹ 17,584/sq.ft.      1
₹ 5,397/sq.ft.       1
₹ 9,074/sq.ft.       1
₹ 5,583/sq.ft.       1
₹ 3,519/sq.ft.       1
₹ 11,194/sq.ft.      1
₹ 6,981/sq.ft.       1
₹ 6,702/sq.ft.       1
₹ 18,333/sq.ft.      1
₹ 4,877/sq.ft.       1
₹ 7,479/sq.ft.       1
₹ 7,400/sq.ft.       1
₹ 16,003/sq.ft.      1
₹ 9,103/sq.ft.       1
₹ 7,727/sq.ft.       1
₹ 45,710/sq.ft.      1
₹ 8,702/sq.ft.       1
₹ 5,950/sq.ft.       1
₹ 26,973/sq.ft.      1
₹ 105,751/sq.ft.     1
₹ 13,750/sq.ft.      1
₹ 6,000/sq.ft.       1
₹ 14,890/sq.ft.      1
₹ 9,210/sq.ft.       1
₹ 6,800/sq.ft.       1
₹ 7,333/sq.ft.       1
₹ 8,101/sq.ft.       1
₹ 14,184/sq.ft.      1
₹ 4,260/sq.ft.       1
₹ 10,582/sq.ft.      1
₹ 9,390/sq.ft.       1
₹ 84,000/sq.ft.      1
₹ 6,938/sq.ft.       1
₹ 38,251/sq.ft.      1
₹ 7,539/sq.ft.       1
₹ 10,067/sq.ft.      1
₹ 1,649/sq.ft.       1
₹ 43,066/sq.ft.      1
₹ 28,898/sq.ft.      1
₹ 28,200/sq.ft.      1
₹ 7,168/sq.ft.       1
₹ 20,444/sq.ft.      1
₹ 53,763/sq.ft.      1
₹ 6,289/sq.ft.       1
₹ 17,857/sq.ft.      1
₹ 7,000/sq.ft.       1
₹ 14,166/sq.ft.      1
₹ 30,968/sq.ft.      1
₹ 7,777/sq.ft.       1
₹ 18,658/sq.ft.      1
₹ 10,484/sq.ft.      1
₹ 160,000/sq.ft.     1
₹ 8,127/sq.ft.       1
₹ 7,555/sq.ft.       1
₹ 49,500/sq.ft.      1
₹ 13,030/sq.ft.      1
₹ 308,333/sq.ft.     1
₹ 10,610/sq.ft.      1
₹ 7,302/sq.ft.       1
₹ 8,155/sq.ft.       1
₹ 10,591/sq.ft.      1
₹ 24,074/sq.ft.      1
₹ 39,062/sq.ft.      1
₹ 5,160/sq.ft.       1
₹ 144,444/sq.ft.     1
₹ 9,615/sq.ft.       1
₹ 6,813/sq.ft.       1
₹ 15,046/sq.ft.      1
₹ 11,583/sq.ft.      1
₹ 6,034/sq.ft.       1
₹ 10,085/sq.ft.      1
₹ 40,611/sq.ft.      1
₹ 48,889/sq.ft.      1
₹ 29,629/sq.ft.      1
₹ 10,740/sq.ft.      1
₹ 17,980/sq.ft.      1
₹ 19,737/sq.ft.      1
₹ 5,093/sq.ft.       1
₹ 25,463/sq.ft.      1
₹ 7,007/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 35,294/sq.ft.      1
₹ 8,254/sq.ft.       1
₹ 5,128/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 15,926/sq.ft.      1
₹ 14,285/sq.ft.      1
₹ 34,307/sq.ft.      1
₹ 51,864/sq.ft.      1
₹ 44,265/sq.ft.      1
₹ 29,444/sq.ft.      1
₹ 39,074/sq.ft.      1
₹ 38,734/sq.ft.      1
₹ 23,442/sq.ft.      1
₹ 41,833/sq.ft.      1
₹ 600,000/sq.ft.     1
₹ 23,889/sq.ft.      1
₹ 10,260/sq.ft.      1
₹ 31,915/sq.ft.      1
₹ 11,102/sq.ft.      1
₹ 8,866/sq.ft.       1
₹ 36,911/sq.ft.      1
₹ 38,150/sq.ft.      1
₹ 15,444/sq.ft.      1
₹ 11,240/sq.ft.      1
₹ 15,437/sq.ft.      1
₹ 14,351/sq.ft.      1
₹ 27,191/sq.ft.      1
₹ 241,666/sq.ft.     1
₹ 33,592/sq.ft.      1
₹ 24,455/sq.ft.      1
₹ 194,444/sq.ft.     1
₹ 18,444/sq.ft.      1
₹ 11,600/sq.ft.      1
₹ 13,492/sq.ft.      1
₹ 10,077/sq.ft.      1
₹ 11,157/sq.ft.      1
₹ 21,495/sq.ft.      1
₹ 42,054/sq.ft.      1
₹ 1,560/sq.ft.       1
₹ 20,741/sq.ft.      1
₹ 13,178/sq.ft.      1
₹ 26,428/sq.ft.      1
₹ 82,540/sq.ft.      1
₹ 18,888/sq.ft.      1
₹ 34,083/sq.ft.      1
₹ 13,501/sq.ft.      1
₹ 20,988/sq.ft.      1
₹ 400,000/sq.ft.     1
₹ 21,296/sq.ft.      1
₹ 18,626/sq.ft.      1
₹ 24,366/sq.ft.      1
₹ 26,298/sq.ft.      1
₹ 24,171/sq.ft.      1
₹ 23,000/sq.ft.      1
₹ 29,697/sq.ft.      1
₹ 6,778/sq.ft.       1
₹ 22,812/sq.ft.      1
₹ 261,194/sq.ft.     1
₹ 178,571/sq.ft.     1
₹ 27,461/sq.ft.      1
₹ 31,686/sq.ft.      1
₹ 23,061/sq.ft.      1
₹ 17,662/sq.ft.      1
₹ 33,200/sq.ft.      1
₹ 14,914/sq.ft.      1
₹ 29,861/sq.ft.      1
₹ 20,068/sq.ft.      1
₹ 16,569/sq.ft.      1
₹ 21,242/sq.ft.      1
₹ 32,562/sq.ft.      1
₹ 22,429/sq.ft.      1
₹ 39,530/sq.ft.      1
₹ 38,889/sq.ft.      1
₹ 57,206/sq.ft.      1
₹ 27,222/sq.ft.      1
₹ 63,554/sq.ft.      1
₹ 10,601/sq.ft.      1
₹ 20,940/sq.ft.      1
₹ 32,253/sq.ft.      1
₹ 23,704/sq.ft.      1
₹ 23,693/sq.ft.      1
₹ 15,989/sq.ft.      1
₹ 19,268/sq.ft.      1
₹ 19,360/sq.ft.      1
₹ 41,762/sq.ft.      1
₹ 23,437/sq.ft.      1
₹ 2,716/sq.ft.       1
₹ 40,850/sq.ft.      1
₹ 15,451/sq.ft.      1
₹ 26,111/sq.ft.      1
₹ 31,790/sq.ft.      1
₹ 235,376/sq.ft.     1
₹ 29,293/sq.ft.      1
₹ 16,004/sq.ft.      1
₹ 27,333/sq.ft.      1
₹ 17,624/sq.ft.      1
₹ 12,938/sq.ft.      1
₹ 9,374/sq.ft.       1
₹ 30,864/sq.ft.      1
₹ 161,849/sq.ft.     1
₹ 16,056/sq.ft.      1
₹ 17,707/sq.ft.      1
₹ 7,718/sq.ft.       1
₹ 25,535/sq.ft.      1
₹ 1,859/sq.ft.       1
₹ 10,579/sq.ft.      1
₹ 42,194/sq.ft.      1
₹ 15,278/sq.ft.      1
₹ 201,388/sq.ft.     1
₹ 17,187/sq.ft.      1
₹ 13,410/sq.ft.      1
₹ 18,928/sq.ft.      1
₹ 10,926/sq.ft.      1
₹ 19,608/sq.ft.      1
₹ 8,089/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 19,607/sq.ft.      1
₹ 40,000/sq.ft.      1
₹ 34,846/sq.ft.      1
₹ 31,444/sq.ft.      1
₹ 32,593/sq.ft.      1
₹ 27,083/sq.ft.      1
₹ 43,210/sq.ft.      1
₹ 31,926/sq.ft.      1
₹ 38,611/sq.ft.      1
₹ 27,911/sq.ft.      1
₹ 29,022/sq.ft.      1
₹ 12,837/sq.ft.      1
₹ 12,198/sq.ft.      1
₹ 35,741/sq.ft.      1
₹ 16,666/sq.ft.      1
₹ 24,170/sq.ft.      1
₹ 7,827/sq.ft.       1
₹ 23,556/sq.ft.      1
₹ 10,035/sq.ft.      1
₹ 28,841/sq.ft.      1
₹ 26,615/sq.ft.      1
₹ 28,490/sq.ft.      1
₹ 62,222/sq.ft.      1
₹ 6,597/sq.ft.       1
₹ 7,870/sq.ft.       1
₹ 28,233/sq.ft.      1
₹ 15,111/sq.ft.      1
₹ 19,820/sq.ft.      1
₹ 1,087/sq.ft.       1
₹ 19,645/sq.ft.      1
₹ 36,883/sq.ft.      1
₹ 27,871/sq.ft.      1
₹ 35,109/sq.ft.      1
₹ 17,692/sq.ft.      1
₹ 38,022/sq.ft.      1
₹ 25,309/sq.ft.      1
₹ 16,990/sq.ft.      1
₹ 14,222/sq.ft.      1
₹ 16,388/sq.ft.      1
₹ 22,075/sq.ft.      1
₹ 11,666/sq.ft.      1
₹ 47,167/sq.ft.      1
₹ 7,937/sq.ft.       1
₹ 20,197/sq.ft.      1
₹ 34,037/sq.ft.      1
₹ 10,123/sq.ft.      1
₹ 28,858/sq.ft.      1
₹ 28,549/sq.ft.      1
₹ 13,513/sq.ft.      1
₹ 20,769/sq.ft.      1
₹ 34,568/sq.ft.      1
₹ 21,097/sq.ft.      1
₹ 25,556/sq.ft.      1
₹ 7,756/sq.ft.       1
₹ 21,825/sq.ft.      1
₹ 16,577/sq.ft.      1
₹ 17,706/sq.ft.      1
₹ 29,074/sq.ft.      1
₹ 122,222/sq.ft.     1
₹ 13,542/sq.ft.      1
₹ 37,778/sq.ft.      1
₹ 31,111/sq.ft.      1
₹ 17,213/sq.ft.      1
₹ 18,620/sq.ft.      1
₹ 17,014/sq.ft.      1
₹ 7,750/sq.ft.       1
₹ 7,172/sq.ft.       1
₹ 29,638/sq.ft.      1
₹ 8,137/sq.ft.       1
₹ 7,582/sq.ft.       1
₹ 18,605/sq.ft.      1
₹ 16,066/sq.ft.      1
₹ 55,556/sq.ft.      1
₹ 38,986/sq.ft.      1
₹ 24,510/sq.ft.      1
₹ 11,428/sq.ft.      1
₹ 22,184/sq.ft.      1
₹ 30,247/sq.ft.      1
₹ 20,370/sq.ft.      1
₹ 31,666/sq.ft.      1
₹ 283,333/sq.ft.     1
₹ 18,008/sq.ft.      1
₹ 12,285/sq.ft.      1
₹ 19,293/sq.ft.      1
₹ 20,599/sq.ft.      1
₹ 173,992/sq.ft.     1
₹ 21,367/sq.ft.      1
₹ 20,299/sq.ft.      1
₹ 41,818/sq.ft.      1
₹ 19,231/sq.ft.      1
₹ 6,875/sq.ft.       1
₹ 14,667/sq.ft.      1
₹ 14,787/sq.ft.      1
₹ 16,319/sq.ft.      1
₹ 18,250/sq.ft.      1
₹ 27,390/sq.ft.      1
₹ 30,728/sq.ft.      1
₹ 41,315/sq.ft.      1
₹ 3,786/sq.ft.       1
₹ 9,349/sq.ft.       1
₹ 23,504/sq.ft.      1
₹ 234,375/sq.ft.     1
₹ 21,786/sq.ft.      1
₹ 15,432/sq.ft.      1
₹ 21,251/sq.ft.      1
₹ 27,160/sq.ft.      1
₹ 35,530/sq.ft.      1
₹ 22,046/sq.ft.      1
₹ 27,132/sq.ft.      1
₹ 22,855/sq.ft.      1
₹ 40,741/sq.ft.      1
₹ 29,333/sq.ft.      1
₹ 19,097/sq.ft.      1
₹ 290,948/sq.ft.     1
₹ 12,393/sq.ft.      1
₹ 22,331/sq.ft.      1
₹ 20,317/sq.ft.      1
₹ 18,088/sq.ft.      1
₹ 16,600/sq.ft.      1
₹ 21,219/sq.ft.      1
₹ 19,125/sq.ft.      1
₹ 18,885/sq.ft.      1
₹ 15,000/sq.ft.      1
₹ 18,814/sq.ft.      1
₹ 14,000/sq.ft.      1
₹ 266,666/sq.ft.     1
₹ 26,502/sq.ft.      1
₹ 18,808/sq.ft.      1
₹ 10,838/sq.ft.      1
₹ 19,847/sq.ft.      1
₹ 12,037/sq.ft.      1
₹ 17,820/sq.ft.      1
₹ 24,390/sq.ft.      1
₹ 26,063/sq.ft.      1
₹ 79,365/sq.ft.      1
₹ 23,932/sq.ft.      1
₹ 24,573/sq.ft.      1
₹ 24,005/sq.ft.      1
₹ 32,870/sq.ft.      1
₹ 33,404/sq.ft.      1
₹ 23,240/sq.ft.      1
₹ 16,071/sq.ft.      1
₹ 51,440/sq.ft.      1
₹ 28,782/sq.ft.      1
₹ 34,491/sq.ft.      1
₹ 34,351/sq.ft.      1
₹ 47,803/sq.ft.      1
₹ 6,230/sq.ft.       1
₹ 33,665/sq.ft.      1
₹ 20,566/sq.ft.      1
₹ 20,349/sq.ft.      1
₹ 24,202/sq.ft.      1
₹ 23,870/sq.ft.      1
₹ 20,026/sq.ft.      1
₹ 28,787/sq.ft.      1
₹ 12,551/sq.ft.      1
₹ 33,129/sq.ft.      1
Name: count, dtype: int64

In [157]:
df['price_per_sqft'] = df['rate'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype(float)

In [158]:
df.head(1)

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0

In [159]:
df['price_in_crore'] = round(((df['area_in_sqft'])*(df['price_per_sqft']))/(10000000.0),2)

In [160]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [161]:
df['property_name'].value_counts()

property_name
4 Bedroom House for sale in Sector 109 Gurgaon                                           25
4 Bedroom House for sale in Sector 48 Gurgaon                                            20
5 Bedroom House for sale in Sector 109 Gurgaon                                           17
5 Bedroom House for sale in DLF Phase 2                                                  16
5 Bedroom House for sale in DLF Phase 1                                                  15
5 Bedroom House for sale in Sector 66 Gurgaon                                            14
4 Bedroom House for sale in Nirvana Country                                              13
4 Bedroom House for sale in Sector 66 Gurgaon                                            12
5 Bedroom House for sale in Nirvana Country                                              10
5 Bedroom House for sale in Sector 33 Gurgaon                                             9
4 Bedroom House for sale in DLF Phase 1                                                   9
4 Bedroom House for sale in Palam Vihar                                                   8
6 Bedroom House for sale in DLF Phase 1                                                   7
3 Bedroom House for sale in Nirvana Country                                               7
3 Bedroom House for sale in Sector 48 Gurgaon                                             7
9 Bedroom House for sale in DLF Phase 2                                                   7
4 Bedroom House for sale in Sector 70A Gurgaon                                            7
5 Bedroom House for sale in Laxman Vihar                                                  6
3 Bedroom House for sale in Laxman Vihar                                                  6
4 Bedroom House for sale in DLF Phase 3                                                   6
4 Bedroom House for sale in Sushant Lok Phase 3                                           6
3 Bedroom House for sale in Sector 109 Gurgaon                                            6
3 Bedroom House for sale in Rajendra Park                                                 6
4 Bedroom House for sale in Sector 82 Gurgaon                                             6
2 Bedroom House for sale in Laxman Vihar                                                  5
5 Bedroom House for sale in Sector 14 Gurgaon                                             5
4 Bedroom House for sale in DLF Phase 2                                                   5
5 Bedroom House for sale in Sector 48 Gurgaon                                             5
3 Bedroom House for sale in Sector 49 Gurgaon                                             5
3 Bedroom House for sale in Sector 4 Gurgaon                                              4
6 Bedroom House for sale in Uppals Southend                                               4
4 Bedroom House for sale in Sector 112 Gurgaon                                            4
4 Bedroom House for sale in Sector 26 Gurgaon                                             4
4 Bedroom House for sale in Sector 31 Gurgaon                                             4
3 Bedroom House for sale in Laxman Vihar Phase 2                                          4
3 Bedroom House for sale in Sector 14 Gurgaon                                             4
5 Bedroom House for sale in Sushant Lok Phase 1                                           4
2 Bedroom House for sale in Palam Vihar Extension                                         4
4 Bedroom House for sale in Sector 54 Gurgaon                                             4
6 Bedroom House for sale in DLF Phase 2                                                   4
16 Bedroom House for sale in DLF Phase 1                                                  4
6 Bedroom House for sale in Palam Vihar                                                   4
2 Bedroom House for sale in Laxman Vihar Phase 2                                          4
4 Bedroom House for sale in DLF Phase 4                                                   4
7 Bedroom House for sale in Sushant Lok Phase 1                                           3
7 Bedroom House for sale in Sector 109 Gurgaon                                            3
4 Bedroom House for sale in Sector 86 Gurgaon                                             3
8 Bedroom House for sale in Sector 46 Gurgaon                                             3
3 Bedroom House for sale in Sohna Road                                                    3
5 Bedroom House for sale in New Colony                                                    3
5 Bedroom House for sale in Uppals Southend                                               3
5 Bedroom House for sale in Sector 111 Gurgaon                                            3
3 Bedroom House for sale in Sector 73 Gurgaon                                             3
4 Bedroom House for sale in Sushant Lok Phase 1                                           3
12 Bedroom House for sale in DLF Phase 2                                                  3
12 Bedroom House for sale in DLF Phase 1                                                  3
3 Bedroom House for sale in Palam Vihar                                                   3
5 Bedroom House for sale in Sector 46 Gurgaon                                             3
4 Bedroom House for sale in Sector 46 Gurgaon                                             3
5 Bedroom House for sale in Sector 57 Gurgaon                                             3
4 Bedroom House for sale in Sector 92 Gurgaon                                             3
1 Bedroom House for sale in Sector 3A Gurgaon                                             3
3 Bedroom House for sale in Sector 70A Gurgaon                                            3
5 Bedroom House for sale in Mianwali Colony                                               3
8 Bedroom House for sale in DLF Phase 3                                                   3
4 Bedroom House for sale in Sector 17B Gurgaon                                            3
3 Bedroom House for sale in Ansal Plaza                                                   3
2 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 3
5 Bedroom House for sale in Sector 72 Gurgaon                                             3
5 Bedroom House for sale in Jyoti Park                                                    3
7 Bedroom House for sale in Sector 48 Gurgaon                                             3
3 Bedroom House for sale in Sector 38 Gurgaon                                             3
5 Bedroom House for sale in Sector 50 Gurgaon                                             3
3 Bedroom House for sale in Sushant Lok Phase 1                                           3
6 Bedroom House for sale in Sector 17 Gurgaon                                             3
10 Bedroom House for sale in Rajiv Nagar                                                  3
3 Bedroom House for sale in Sector 82 Gurgaon                                             3
1 Bedroom House for sale in Sector 39 Gurgaon                                             3
12 Bedroom House for sale in Uppals Southend                                              3
1 Bedroom House for sale in Sushant Lok Phase 1                                           3
3 Bedroom House for sale in Ashok Vihar                                                   3
4 Bedroom House for sale in Sector 103 Gurgaon                                            3
6 Bedroom House for sale in Sector 33 Gurgaon                                             3
6 Bedroom House for sale in Greenwood City                                                3
5 Bedroom House for sale in Palam Vihar                                                   3
6 Bedroom House for sale in Sushant Lok Phase 3                                           3
8 Bedroom House for sale in Palam Vihar                                                   2
12 Bedroom House for sale in Sector 56 Gurgaon                                            2
5 Bedroom House for sale in Greenwood City                                                2
4 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
10 Bedroom House for sale in South City 1                                                 2
3 Bedroom House for sale in Rosewood                                                      2
3 Bedroom House for sale in Sector 40 Gurgaon                                             2
4 Bedroom House for sale in Sector 55 Gurgaon                                             2
4 Bedroom House for sale in Sector 91 Gurgaon                                             2
5 Bedroom House for sale in Sector 56 Gurgaon                                             2
8 Bedroom House for sale in Sushant Lok Phase 1                                           2
9 Bedroom House for sale in South City 1                                                  2
3 Bedroom House for sale in Sector 7 Gurgaon                                              2
6 Bedroom House for sale in Sector 22 Gurgaon                                             2
2 Bedroom House for sale in Narsinghpur                                                   2
4 Bedroom House for sale in Sector 72 Gurgaon                                             2
4 Bedroom House for sale in Sector 23 Gurgaon                                             2
12 Bedroom House for sale in Sector 40 Gurgaon                                            2
9 Bedroom House for sale in Sector 47 Gurgaon                                             2
4 Bedroom House for sale in Sector 4 Gurgaon                                              2
2 Bedroom House for sale in Sector 70A Gurgaon                                            2
16 Bedroom House for sale in DLF Phase 4                                                  2
3 Bedroom House for sale in Bissar                                                        2
9 Bedroom House for sale in Sector 38 Gurgaon                                             2
9 Bedroom House for sale in Sector 9 Gurgaon                                              2
12 Bedroom House for sale in Sushant Lok Phase 1                                          2
3 Bedroom House for sale in Sector 26 Gurgaon                                             2
5 Bedroom House for sale in Sector 70A Gurgaon                                            2
5 Bedroom House for sale in B Block Sushant Lok Phase 1                                   2
6 Bedroom House for sale in Sushant Lok Phase 1                                           2
3 Bedroom House for sale in Hira Nagar                                                    2
3 Bedroom House for sale in Sushant Lok Phase 2                                           2
2 Bedroom House for sale in Sector-33 Sohna                                               2
9 Bedroom House for sale in Sector 45 Gurgaon                                             2
2 Bedroom House for sale in Daulatabad                                                    2
3 Bedroom House for sale in Sector 23A Gurgaon                                            2
3 Bedroom House for sale in Sector 63A Gurgaon                                            2
4 Bedroom House for sale in Sector 65 Gurgaon                                             2
3 Bedroom House for sale in Devilal Colony                                                2
2 Bedroom House for sale in Sector 5 Gurgaon                                              2
5 Bedroom House for sale in Sector 3 Gurgaon                                              2
2 Bedroom House for sale in Sohna                                                         2
4 Bedroom House for sale in Laxman Vihar Phase 2                                          2
6 Bedroom House for sale in Sector 50 Gurgaon                                             2
1 Bedroom House for sale in Laxman Vihar                                                  2
9 Bedroom House for sale in Palam Vihar Extension                                         2
5 Bedroom House for sale in Sector 5 Gurgaon                                              2
8 Bedroom House for sale in Sector 56 Gurgaon                                             2
2 Bedroom House for sale in Vishnu Garden                                                 2
2 Bedroom House for sale in Sohna Road                                                    2
5 Bedroom House for sale in Sector 11 Gurgaon                                             2
2 Bedroom House for sale in Rajendra Park                                                 2
5 Bedroom House for sale in Sector 7 Gurgaon                                              2
4 Bedroom House for sale in Jacobpura                                                     2
5 Bedroom House for sale in DLF Phase 3                                                   2
6 Bedroom House for sale in Sector 67 Gurgaon                                             2
3 Bedroom House for sale in DLF Phase 1                                                   2
4 Bedroom House for sale in Sector-33 Sohna                                               2
19 Bedroom House for sale in Sector 17A Gurgaon                                           2
4 Bedroom House for sale in Sector 56 Gurgaon                                             2
6 Bedroom House for sale in Sector 38 Gurgaon                                             2
12 Bedroom House for sale in Sector 46 Gurgaon                                            2
5 Bedroom House for sale in Sohna Road                                                    2
7 Bedroom House for sale in DLF Phase 3                                                   2
2 Bedroom House for sale in Sheetla Colony                                                2
3 Bedroom House for sale in Baldev Nagar                                                  2
5 Bedroom House for sale in Sector 53 Gurgaon                                             2
6 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sector 31 Gurgaon                                             2
10 Bedroom House for sale in Shivpuri                                                     2
2 Bedroom House for sale in Garhi Harsaru                                                 2
3 Bedroom House for sale in DLF Phase 2                                                   2
3 Bedroom House for sale in Arjun Nagar                                                   2
2 Bedroom House for sale in Baldev Nagar                                                  2
4 Bedroom House for sale in Arjun Nagar                                                   2
4 Bedroom House for sale in Sector 6 Gurgaon                                              2
4 Bedroom House for sale in Sector 3 Gurgaon                                              2
9 Bedroom House for sale in Palam Vihar                                                   2
5 Bedroom House for sale in Sector 39 Gurgaon                                             2
4 Bedroom House for sale in Rajendra Park                                                 2
3 Bedroom House for sale in Sushant Lok Phase 3                                           2
2 Bedroom House for sale in Devilal Colony                                                2
5 Bedroom House for sale in Ashok Vihar Phase 2                                           2
5 Bedroom House for sale in Sector 108 Gurgaon                                            2
3 Bedroom House for sale in Dharam Colony                                                 2
4 Bedroom House for sale in Saraswati Vihar                                               2
2 Bedroom House for sale in Sector 8 Gurgaon                                              2
1 Bedroom House for sale in Mianwali Colony                                               2
4 Bedroom House for sale in Laxman Vihar                                                  2
5 Bedroom House for sale in Bhim Nagar                                                    2
12 Bedroom House for sale in Malibu Town                                                  2
9 Bedroom House for sale in C Block Sushant Lok Phase 1                                   2
1 Bedroom House for sale in Ashok Vihar Phase 3 Extension                                 2
7 Bedroom House for sale in Rajendra Park                                                 2
2 Bedroom House for sale in Sector 56 Gurgaon                                             2
2 Bedroom House for sale in Sector 7 Gurgaon                                              2
4 Bedroom House for sale in Sector 67 Gurgaon                                             2
9 Bedroom House for sale in Sector 40 Gurgaon                                             2
10 Bedroom House for sale in DLF Phase 3                                                  2
7 Bedroom House for sale in DLF Phase 1                                                   2
6 Bedroom House for sale in Sector 14 Gurgaon                                             2
6 Bedroom House for sale in DLF Phase 4                                                   2
6 Bedroom House for sale in New Palam Vihar Phase 1                                       1
13 Bedroom House for sale in DLF Phase 3                                                  1
8 Bedroom House for sale in Sector 17 Gurgaon                                             1
16 Bedroom House for sale in Sushant Lok Phase 1                                          1
16 Bedroom House for sale in Sector 56 Gurgaon                                            1
4 Bedroom House for sale in Sector 33 Gurgaon                                             1
5 Bedroom House for sale in Sector 27 Gurgaon                                             1
16 Bedroom House for sale in DLF Phase 2                                                  1
12 Bedroom House for sale in Sector 27 Gurgaon                                            1
5 Bedroom House for sale in Sector 31 Gurgaon                                             1
4 Bedroom House for sale in Suncity                                                       1
7 Bedroom House for sale in Sector 23 Gurgaon                                             1
9 Bedroom House for sale in A Block Sushant Lok Phase 1                                   1
18 Bedroom House for sale in Suncity                                                      1
5 Bedroom House for sale in Sector 23 Gurgaon                                             1
5 Bedroom House for sale in A Block Sushant Lok Phase 1                                   1
16 Bedroom House for sale in Sector 40 Gurgaon                                            1
4 Bedroom House for sale in Sector 42 Gurgaon                                             1
3 Bedroom House for sale in B Block Sushant Lok Phase 1                                   1
3 Bedroom House for sale in Sector 105 Gurgaon                                            1
4 Bedroom House for sale in Part 3 Sector 5 Gurgaon                                       1
1 Bedroom House for sale in Sohna                                                         1
4 Bedroom House for sale in Sector 63 Gurgaon                                             1
7 Bedroom House for sale in Lucknow                                                       1
4 Bedroom House for sale in Pataudi Road                                                  1
8 Bedroom House for sale in Surya Vihar                                                   1
5 Bedroom House for sale in Khandsa                                                       1
5 Bedroom House for sale in Ravi Nagar                                                    1
3 Bedroom House for sale in Maruti Kunj                                                   1

In [162]:
df['property_name'].isnull().sum()

np.int64(0)

In [163]:
df['bedRoom'] = df['property_name'].str.split('Bedroom').str.get(0).str.strip().astype(int)

In [164]:
df['bathroom'] = df['bedRoom']

In [165]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,5,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,5,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [166]:
df['balcony'].isnull().sum()

np.int64(57)

In [167]:
df['balcony'].value_counts()

balcony
3+ Balconies    366
2 Balconies     221
3 Balconies     161
No Balcony      118
1 Balcony       108
Name: count, dtype: int64

In [168]:
df['balcony'] = df['balcony'].fillna('No Balcony')

In [169]:
df['balcony'].isnull().sum()

np.int64(0)

In [170]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.strip()

In [171]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,5,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [172]:
df['additionalRoom'].isnull().sum()

np.int64(453)

In [173]:
df['additionalRoom'] = df['additionalRoom'].fillna('not available')

In [174]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5,5,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [175]:
df = df.drop(columns=['price','rate','area'])

In [176]:
df['society'].isnull().sum()

np.int64(586)

In [177]:
df.head()

,property_name,society,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,Plot area 539(50.07 sq.m.),5,5,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [178]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [179]:
df['floorNum'] = df['floorNum'].ffill().str.split(' ').str.get(0).str.strip().astype(int)

In [180]:
df.head()

,property_name,society,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,Plot area 539(50.07 sq.m.),5,5,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20,105751.0,5.69
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96,38251.0,2.10
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51,43066.0,5.01
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73,53763.0,3.01

In [181]:
# df['facing'] = df['facing'].ffill()

In [182]:
df.head(1)

,property_name,society,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft,price_per_sqft,price_in_crore
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89,20115.0,5.24

In [183]:
df = df[['society','price_in_crore','price_per_sqft','areaWithType','bedRoom','bathroom','balcony','additionalRoom','address','floorNum','facing','agePossession','nearbyLocations','description','furnishDetails','features','rating','property_type','location','area_in_sqft']]

In [184]:
df.head()

,society,price_in_crore,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_type,location,area_in_sqft
0,Bptp Visionnaire,5.24,20115.0,Plot area 290(242.48 sq.m.),5,5,3+,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",House,Sector 70A Gurgaon,2604.89
1,NaN,5.69,105751.0,Plot area 539(50.07 sq.m.),5,5,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,House,Sector 21A Faridabad,538.20
2,NaN,2.10,38251.0,Plot area 61(51 sq.m.),10,10,3+,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,548.96
3,NaN,5.01,43066.0,Plot area 129(107.86 sq.m.),21,21,3+,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",House,Sector 54 Gurgaon,1162.51
4,NaN,3.01,53763.0,Plot area 62(51.84 sq.m.),12,12,3+,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",House,Sushant Lok Phase 1,559.73

In [185]:
df.to_csv('house_cleaned.csv',index=False)